--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("yuri_engineer/res/11-di.png",0)

bg:setFlippedX(false)
bg:setFlippedY(false)

bg:setScale9Enabled(false)
bg:setCapInsets(cc.rect(0,0,499,89))
bg:setTouchEnabled(false)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setLocalZOrder(0)
bg:setTag(371)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setVisible(true)
bg:setAnchorPoint(0.5, 0.5)
bg:setPosition(248, 42.5764)
bg:setScaleX(1)
bg:setScaleY(1)
bg:setRotation(0)
bg:setRotationSkewX(0)
bg:setRotationSkewY(0)
bg:setOpacity(255)
bg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(499, 89))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-1.5)
layout:setRightMargin(-497.5)
layout:setTopMargin(-87.0764)
layout:setBottomMargin(-1.9236)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(bg)

--Create Text_rank
local Text_rank = ccui.Text:create()
Text_rank:ignoreContentAdaptWithSize(true)
Text_rank:setTextAreaSize(cc.size(0, 0))
Text_rank:setFontName("Resources/font/ttf/black_body.TTF")
Text_rank:setFontSize(24)
Text_rank:setString([[5555]])
Text_rank:setTextHorizontalAlignment(0)
Text_rank:setTextVerticalAlignment(0)
Text_rank:setTouchScaleChangeEnabled(false)
Text_rank:setFlippedX(false)
Text_rank:setFlippedY(false)
Text_rank:enableOutline(cc.c4b(0, 0, 0, 255), 1)
Text_rank:setTouchEnabled(false)
Text_rank:setLayoutComponentEnabled(true)
Text_rank:setName("Text_rank")
Text_rank:setLocalZOrder(0)
Text_rank:setTag(68)
Text_rank:setCascadeColorEnabled(true)
Text_rank:setCascadeOpacityEnabled(true)
Text_rank:setVisible(true)
Text_rank:setAnchorPoint(0.5, 0.5)
Text_rank:setPosition(67, 44.5)
Text_rank:setScaleX(1)
Text_rank:setScaleY(1)
Text_rank:setRotation(0)
Text_rank:setRotationSkewX(0)
Text_rank:setRotationSkewY(0)
Text_rank:setOpacity(255)
Text_rank:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Text_rank)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1343)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.1283)
layout:setPercentHeight(0.3258)

layout:setSize(cc.size(64, 29))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(35)
layout:setRightMargin(400)
layout:setTopMargin(30)
layout:setBottomMargin(30)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(Text_rank)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize(cc.size(0, 0))
Text_name:setFontName("Resources/font/ttf/black_body.TTF")
Text_name:setFontSize(20)
Text_name:setString([[玩家名字七个字]])
Text_name:setTextHorizontalAlignment(0)
Text_name:setTextVerticalAlignment(0)
Text_name:setTouchScaleChangeEnabled(false)
Text_name:setFlippedX(false)
Text_name:setFlippedY(false)
Text_name:enableOutline(cc.c4b(0, 0, 0, 255), 1)
Text_name:setTouchEnabled(false)
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setLocalZOrder(0)
Text_name:setTag(69)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setVisible(true)
Text_name:setAnchorPoint(0.5, 0.5)
Text_name:setPosition(249.5, 44.5)
Text_name:setScaleX(1)
Text_name:setScaleY(1)
Text_name:setRotation(0)
Text_name:setRotationSkewX(0)
Text_name:setRotationSkewY(0)
Text_name:setOpacity(255)
Text_name:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.2826)
layout:setPercentHeight(0.2809)

layout:setSize(cc.size(141, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(179)
layout:setRightMargin(179)
layout:setTopMargin(32)
layout:setBottomMargin(32)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(Text_name)

--Create Text_power
local Text_power = ccui.Text:create()
Text_power:ignoreContentAdaptWithSize(true)
Text_power:setTextAreaSize(cc.size(0, 0))
Text_power:setFontName("Resources/font/ttf/black_body.TTF")
Text_power:setFontSize(20)
Text_power:setString([[100]])
Text_power:setTextHorizontalAlignment(0)
Text_power:setTextVerticalAlignment(0)
Text_power:setTouchScaleChangeEnabled(false)
Text_power:setFlippedX(false)
Text_power:setFlippedY(false)
Text_power:enableOutline(cc.c4b(0, 0, 0, 255), 1)
Text_power:setTouchEnabled(false)
Text_power:setLayoutComponentEnabled(true)
Text_power:setName("Text_power")
Text_power:setLocalZOrder(0)
Text_power:setTag(71)
Text_power:setCascadeColorEnabled(true)
Text_power:setCascadeOpacityEnabled(true)
Text_power:setVisible(true)
Text_power:setAnchorPoint(0.5, 0.5)
Text_power:setPosition(431.3398, 44.1426)
Text_power:setScaleX(1)
Text_power:setScaleY(1)
Text_power:setRotation(0)
Text_power:setRotationSkewX(0)
Text_power:setRotationSkewY(0)
Text_power:setOpacity(255)
Text_power:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Text_power)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.8644)
layout:setPositionPercentY(0.496)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.2385)
layout:setPercentHeight(0.2809)

layout:setSize(cc.size(40, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(411.3398)
layout:setRightMargin(47.6602)
layout:setTopMargin(32.3574)
layout:setBottomMargin(31.6426)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(Text_power)

--Create Image_rank
local Image_rank = ccui.ImageView:create()
Image_rank:ignoreContentAdaptWithSize(false)
Image_rank:loadTexture("yuri_engineer/res/1nd.png",0)

Image_rank:setFlippedX(false)
Image_rank:setFlippedY(false)

Image_rank:setScale9Enabled(false)
Image_rank:setCapInsets(cc.rect(0,0,75,32))
Image_rank:setTouchEnabled(false)
Image_rank:setLayoutComponentEnabled(true)
Image_rank:setName("Image_rank")
Image_rank:setLocalZOrder(0)
Image_rank:setTag(943)
Image_rank:setCascadeColorEnabled(true)
Image_rank:setCascadeOpacityEnabled(true)
Image_rank:setVisible(true)
Image_rank:setAnchorPoint(0.5, 0.5)
Image_rank:setPosition(66, 44.5)
Image_rank:setScaleX(1)
Image_rank:setScaleY(1)
Image_rank:setRotation(0)
Image_rank:setRotationSkewX(0)
Image_rank:setRotationSkewY(0)
Image_rank:setOpacity(255)
Image_rank:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Image_rank)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.1323)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.1503)
layout:setPercentHeight(0.3596)

layout:setSize(cc.size(75, 32))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(28.5)
layout:setRightMargin(395.5)
layout:setTopMargin(28.5)
layout:setBottomMargin(28.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(Image_rank)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

