--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("passenger/res/passengerui.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("passenger/res/3.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setLocalZOrder(0)
Sprite_1:setTag(190)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setVisible(true)
Sprite_1:setAnchorPoint(0.5, 0.5)
Sprite_1:setPosition(20.0002, 20.0005)
Sprite_1:setScaleX(1)
Sprite_1:setScaleY(1)
Sprite_1:setRotation(0)
Sprite_1:setRotationSkewX(0)
Sprite_1:setRotationSkewY(0)
Sprite_1:setOpacity(255)
Sprite_1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(19, 24))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(10.5002)
layout:setRightMargin(-29.5002)
layout:setTopMargin(-32.0005)
layout:setBottomMargin(8.0005)
Sprite_1:setFlippedX(false)
Sprite_1:setFlippedY(false)
Node:addChild(Sprite_1)

--Create name
local name = ccui.Text:create()
name:ignoreContentAdaptWithSize(true)
name:setTextAreaSize(cc.size(0, 0))
name:setFontName("Resources/font/ttf/black_body.TTF")
name:setFontSize(20)
name:setString([[防  御  力]])
name:setTextHorizontalAlignment(0)
name:setTextVerticalAlignment(0)
name:setTouchScaleChangeEnabled(false)
name:setFlippedX(false)
name:setFlippedY(false)
name:enableShadow(cc.c4b(0, 0, 0, 255), cc.size(2, -2), 0)
name:setTouchEnabled(false)
name:setLayoutComponentEnabled(true)
name:setName("name")
name:setLocalZOrder(0)
name:setTag(191)
name:setCascadeColorEnabled(true)
name:setCascadeOpacityEnabled(true)
name:setVisible(true)
name:setAnchorPoint(0, 0.5)
name:setPosition(44.2962, 22.0003)
name:setScaleX(1)
name:setScaleY(1)
name:setRotation(0)
name:setRotationSkewX(0)
name:setRotationSkewY(0)
name:setOpacity(255)
name:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(name)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(4.7895)
layout:setPercentHeight(0.9583)

layout:setSize(cc.size(84, 23))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(44.2962)
layout:setRightMargin(-128.2962)
layout:setTopMargin(-33.5003)
layout:setBottomMargin(10.5003)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(name)

--Create attr
local attr = ccui.Text:create()
attr:ignoreContentAdaptWithSize(true)
attr:setTextAreaSize(cc.size(0, 0))
attr:setFontName("Resources/font/ttf/black_body.TTF")
attr:setFontSize(20)
attr:setString([[+12315]])
attr:setTextHorizontalAlignment(0)
attr:setTextVerticalAlignment(0)
attr:setTouchScaleChangeEnabled(false)
attr:setFlippedX(false)
attr:setFlippedY(false)
attr:enableShadow(cc.c4b(0, 0, 0, 255), cc.size(2, -2), 0)
attr:enableOutline(cc.c4b(0, 0, 0, 255), 1)
attr:setTouchEnabled(false)
attr:setLayoutComponentEnabled(true)
attr:setName("attr")
attr:setLocalZOrder(0)
attr:setTag(192)
attr:setCascadeColorEnabled(true)
attr:setCascadeOpacityEnabled(true)
attr:setVisible(true)
attr:setAnchorPoint(0, 0.5)
attr:setPosition(170.2969, 22.0003)
attr:setScaleX(1)
attr:setScaleY(1)
attr:setRotation(0)
attr:setRotationSkewX(0)
attr:setRotationSkewY(0)
attr:setOpacity(255)
attr:setColor(cc.c3b(61, 219, 61))
layout = ccui.LayoutComponent:bindLayoutComponent(attr)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(4.4737)
layout:setPercentHeight(1.0417)

layout:setSize(cc.size(79, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(170.2969)
layout:setRightMargin(-249.2969)
layout:setTopMargin(-34.5003)
layout:setBottomMargin(9.5003)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(attr)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

