--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create cell_bg
cc.SpriteFrameCache:getInstance():addSpriteFrames("legion_war/res/legion_war_2.plist")
local cell_bg = cc.Sprite:createWithSpriteFrameName("legion_war/res/2.png")
cell_bg:setName("cell_bg")
cell_bg:setLocalZOrder(0)
cell_bg:setTag(59)
cell_bg:setCascadeColorEnabled(true)
cell_bg:setCascadeOpacityEnabled(true)
cell_bg:setVisible(true)
cell_bg:setAnchorPoint(0.5, 0.5)
cell_bg:setPosition(314.0826, 472.3531)
cell_bg:setScaleX(1)
cell_bg:setScaleY(1)
cell_bg:setRotation(0)
cell_bg:setRotationSkewX(0)
cell_bg:setRotationSkewY(0)
cell_bg:setOpacity(255)
cell_bg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(cell_bg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(618, 61))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(5.0826)
layout:setRightMargin(-623.0826)
layout:setTopMargin(-502.8531)
layout:setBottomMargin(441.8531)
cell_bg:setFlippedX(false)
cell_bg:setFlippedY(false)
Node:addChild(cell_bg)

--Create title
local title = ccui.Text:create()
title:ignoreContentAdaptWithSize(true)
title:setTextAreaSize(cc.size(0, 0))
title:setFontName("Resources/font/ttf/black_body.TTF")
title:setFontSize(32)
title:setString([[初赛第一轮]])
title:setTextHorizontalAlignment(0)
title:setTextVerticalAlignment(0)
title:setTouchScaleChangeEnabled(false)
title:setFlippedX(false)
title:setFlippedY(false)
title:enableShadow(cc.c4b(0, 0, 0, 255), cc.size(3, -3), 0)
title:enableOutline(cc.c4b(0, 0, 0, 255), 1)
title:setTouchEnabled(false)
title:setLayoutComponentEnabled(true)
title:setName("title")
title:setLocalZOrder(0)
title:setTag(64)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
title:setVisible(true)
title:setAnchorPoint(0.5, 0.5)
title:setPosition(308.9999, 31.0399)
title:setScaleX(1)
title:setScaleY(1)
title:setRotation(12)
title:setRotationSkewX(12)
title:setRotationSkewY(0)
title:setOpacity(255)
title:setColor(cc.c3b(255, 255, 153))
layout = ccui.LayoutComponent:bindLayoutComponent(title)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5089)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(161, 39))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(228.4999)
layout:setRightMargin(228.5001)
layout:setTopMargin(10.4601)
layout:setBottomMargin(11.5399)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
cell_bg:addChild(title)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

