var ssoType = "testSSO"
	if (cc.sys.os === cc.sys.OS_IOS) {
		ssoType = jsb.reflection.callStaticMethod("GameConfig", "getSSOType");
	} else if (cc.sys.os === cc.sys.OS_ANDROID) {

	}
var ccbi_dir = "tc";
switch (ssoType) {
case "testSSO":
case "tgameCnSSO":
default:
	ccbi_dir = "tc";
break;
}
var ccbi_res = {
		LoginView_ccbi : ccbi_dir +"/ccbi/ccbResources/LoginView.ccbi",
		LoginMain_ccbi : ccbi_dir + "/ccbi/ccbResources/LoginMainView.ccbi",
		MainLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/MainView.ccbi",
		HomeLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/HomeView.ccbi",
		MainPageHeroBgView1_ccbi : ccbi_dir + "/ccbi/ccbResources/MainPageHeroBgView1.ccbi",
		MainPageHeroBgView2_ccbi : ccbi_dir + "/ccbi/ccbResources/MainPageHeroBgView2.ccbi",
		MainPageHeroBgView3_ccbi : ccbi_dir + "/ccbi/ccbResources/MainPageHeroBgView3.ccbi",
		MainPageHeroBgView4_ccbi : ccbi_dir + "/ccbi/ccbResources/MainPageHeroBgView4.ccbi",
		MainPageHeroBgView5_ccbi : ccbi_dir + "/ccbi/ccbResources/MainPageHeroBgView5.ccbi",
		CaptainInfoView_ccbi : ccbi_dir + "/ccbi/ccbResources/CaptainInfoView.ccbi",
		vipDetailView_ccbi : ccbi_dir + "/ccbi/ccbResources/vipDetailView.ccbi",
		HeroesView_ccbi : ccbi_dir + "/ccbi/ccbResources/HeroesView.ccbi",
		HuoBanCell_ccbi : ccbi_dir + "/ccbi/ccbResources/HuoBanCell.ccbi",
		HunPoCell_ccbi : ccbi_dir + "/ccbi/ccbResources/HunPoCell.ccbi",
		GotoLogueCell_ccbi : ccbi_dir + "/ccbi/ccbResources/GoToLogueCell.ccbi",
		FarewellView_ccbi : ccbi_dir + "/ccbi/ccbResources/FarewellView.ccbi",
		SelHeroFarewellView_ccbi : ccbi_dir + "/ccbi/ccbResources/SelHeroFarewellView.ccbi",
		SelectSMP_ccbi : ccbi_dir + "/ccbi/ccbResources/SelectSMPView.ccbi",
		OnFormCell_ccbi : ccbi_dir + "/ccbi/ccbResources/OnFormCell.ccbi",
		TeamView_ccbi : ccbi_dir + "/ccbi/ccbResources/TeamView.ccbi",
		TeamViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/TeamViewCell.ccbi",
		AwakeTeamViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/AwakeTeamViewCell.ccbi",
		CultureView_ccbi : ccbi_dir + "/ccbi/ccbResources/CultureView.ccbi",
		ShadowViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/shadowViewCell.ccbi",
		ChangeTeamView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChangeTeamView.ccbi",
		OnFormView_ccbi : ccbi_dir + "/ccbi/ccbResources/OnFormView.ccbi",
		TeamAllViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/TeamAllViewCell.ccbi",
		LaLaViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/LalaViewCell.ccbi",
		BreakHeroView_ccbi : ccbi_dir + "/ccbi/ccbResources/BreakHeroView.ccbi",
		LaLaUpdateLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/LaLaViewUpdata.ccbi",
		ConfirmCard_ccbi : ccbi_dir + "/ccbi/ccbResources/SimpleConfirmCard.ccbi",
		ShopBuySomePopUp_ccbi : ccbi_dir + "/ccbi/ccbResources/ShopBuySomePopUp.ccbi",
		SkillView_ccbi : ccbi_dir + "/ccbi/ccbResources/SkillView.ccbi",
		GotoAdventure_ccbi : ccbi_dir + "/ccbi/ccbResources/GoToDaMaoXian.ccbi",
		TitleTipsLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/TitleTipsLayerView.ccbi",
		SkillTableViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/SkillTableViewCell.ccbi",
		SkillBreak_ccbi : ccbi_dir + "/ccbi/ccbResources/BreakSkillVIewLayer.ccbi",
		SkillBreakSelect_ccbi : ccbi_dir + "/ccbi/ccbResources/BreakSkillSelectView.ccbi",
		SkillSelectCell_ccbi : ccbi_dir + "/ccbi/ccbResources/SkillSelectCell.ccbi",
		SkillBreakResult_ccbi : ccbi_dir + "/ccbi/ccbResources/BreakSkillResult.ccbi",
		TrainShadowView_ccbi : ccbi_dir + "/ccbi/ccbResources/TrainShadowView.ccbi",
		TrainShadowContentView_ccbi : ccbi_dir + "/ccbi/ccbResources/TrainShadowContentView.ccbi",
		TrainShadowCell_ccbi : ccbi_dir + "/ccbi/ccbResources/TrainShadowCell.ccbi",
		ShadowWaveView_ccbi : ccbi_dir + "/ccbi/ccbResources/ShadowWaveView.ccbi",
		ShadowWaveTableCell_ccbi : ccbi_dir + "/ccbi/ccbResources/ShadowWaveTableCell.ccbi",
		ShadowBoxView_ccbi : ccbi_dir + "/ccbi/ccbResources/ShadowBoxView.ccbi",
		ShadowBoxTableCell_ccbi : ccbi_dir + "/ccbi/ccbResources/ShadowBoxTableCell.ccbi",
		ShadowUpdateView_ccbi : ccbi_dir + "/ccbi/ccbResources/ShadowUpdateView.ccbi",
		TrainShadowCell_ccbi : ccbi_dir + "res/tc/ccbi/ccbResources/TrainShadowCell.ccbi",
		TrainShadowTrainOther_ccbi : ccbi_dir + "/ccbi/ccbResources/TrainShadowTrainOther.ccbi",
		PackageLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/WarehouseView.ccbi",
		PackageCell_ccbi : ccbi_dir + "/ccbi/ccbResources/WarehouseCell.ccbi",
		GetSomeRewardPopUp_ccbi : ccbi_dir + "/ccbi/ccbResources/GetSomeRewardPopUp.ccbi",
		ItemDetailInfoView_ccbi : ccbi_dir + "/ccbi/ccbResources/ItemDetailInfoView.ccbi",
		GetSomeRewardCell_ccbi : ccbi_dir + "/ccbi/ccbResources/GetSomeRewardCell.ccbi",	
		EquipsLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/EquipmentsView.ccbi",
		GotoSailCell_ccbi : ccbi_dir + "/ccbi/ccbResources/GoToQiHangeCell.ccbi",
		EquipSellCell_ccbi : ccbi_dir + "/ccbi/ccbResources/EquipSellCell.ccbi",
		EquipCell_ccbi : ccbi_dir + "/ccbi/ccbResources/EquipmentsTableCell.ccbi",
		EquipSellLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/EquipSellView.ccbi",
		EquipSellSelectCell_ccbi : ccbi_dir + "/ccbi/ccbResources/EquipmentsCellSelectTableCell.ccbi",
		EquipUpdateLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/EquipUpdateView.ccbi",
		RefineStuffCell_ccbi : ccbi_dir + "/ccbi/ccbResources/EquipRefineMaterialCell.ccbi",
		EquipRefineResult_ccbi : ccbi_dir + "/ccbi/ccbResources/EquipRefineResult.ccbi",
		DailyView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyView.ccbi",
		DailyYuekaView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyYuekaView.ccbi",
		DailySigninView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailySignInView.ccbi",
		EatView_ccbi : ccbi_dir + "/ccbi/ccbResources/EatView.ccbi",
		GoldBellView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyGoldClockView.ccbi",
		MonthCardView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyYuekaView.ccbi",
		MysteryShopView_ccbi : ccbi_dir + "/ccbi/ccbResources/MysteryShopView.ccbi",
		Invite_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyInvite.ccbi",
		DailyBluckSing_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyBluckSing.ccbi",
		EatView_ccbi : ccbi_dir + "/ccbi/ccbResources/EatView.ccbi",
		TeamHakiViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/TeamHakiViewCell.ccbi",
		HandBookView_ccbi : ccbi_dir + "/ccbi/ccbResources/HandBookView.ccbi",
		HandBookCell_ccbi : ccbi_dir + "/ccbi/ccbResources/HandBookCell.ccbi",
		HakiSkillView_ccbi :ccbi_dir + "/ccbi/ccbResources/HakiSkillView.ccbi",
		HakiSkillCellView_ccbi : ccbi_dir + "/ccbi/ccbResources/HakiSkillCellView.ccbi",
		HakiDetailView_ccbi : ccbi_dir + "/ccbi/ccbResources/HakiDetailView.ccbi",
		NewsView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewsView.ccbi",
		NewsViewTableCell_ccbi : ccbi_dir + "/ccbi/ccbResources/NewsViewTableCell.ccbi",
		AdventureView_ccbi : ccbi_dir + "/ccbi/ccbResources/AdventureView.ccbi",
		NewWorldWinView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldWinView.ccbi",
		NewWorldLoseView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldLoseView.ccbi",
		NewWorldOverView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldOverView.ccbi",
		newWorldRankCell_ccbi : ccbi_dir + "/ccbi/ccbResources/newWorldRankCell.ccbi",
		NewWorldRankView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldRankView.ccbi",
		NewWorldFifthView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldFifthView.ccbi",
		NewWorldFirstView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldFirstView.ccbi",
		NewWorldThirdView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldThirdView.ccbi",
		NewWorldFourthView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldFourthView.ccbi",
		NewWorldSecondView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldSecondView.ccbi",
		NewWorldSweepWinView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldSweepWinView.ccbi",
		NewWorldFirstViewHelp_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldFirstViewHelp.ccbi",
		NewWorldSweepLoseView_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldSweepLoseView.ccbi",
		BossView_ccbi : ccbi_dir + "/ccbi/ccbResources/BossView.ccbi",
		BossResultView_ccbi : ccbi_dir + "/ccbi/ccbResources/BossResultView.ccbi",
		BossRankCell_ccbi : ccbi_dir + "/ccbi/ccbResources/BossRankCell.ccbi",
		BossRankView_ccbi : ccbi_dir + "/ccbi/ccbResources/BossRankView.ccbi",
		BossDefeatCell_ccbi : ccbi_dir + "/ccbi/ccbResources/BossDefeatCell.ccbi",
		BossChallengeView_ccbi : ccbi_dir + "/ccbi/ccbResources/BossChallengeView.ccbi",
		FightLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/FightingView.ccbi",
		FightBg1_ccbi : ccbi_dir + "/ccbi/ccbResources/FightingBg_1.ccbi",
		FightBg2_ccbi : ccbi_dir + "/ccbi/ccbResources/FightingBg_2.ccbi",
		FightBg3_ccbi : ccbi_dir + "/ccbi/ccbResources/FightingBg_3.ccbi",
		FightBg4_ccbi : ccbi_dir + "/ccbi/ccbResources/FightingBg_4.ccbi",
		FightBg5_ccbi : ccbi_dir + "/ccbi/ccbResources/FightingBg_5.ccbi",
		FightBg6_ccbi : ccbi_dir + "/ccbi/ccbResources/FightingBg_6.ccbi",
		FightBg1_Ani_ccbi : ccbi_dir + "/ccbi/ccbResources/fightingBg_1_Animation.ccbi",
		FightRound_ccbi : ccbi_dir + "/ccbi/ccbResources/roundFight.ccbi",
		FightWin_ccbi : ccbi_dir + "/ccbi/ccbResources/congratulations.ccbi",
		FightLose_ccbi : ccbi_dir + "/ccbi/ccbResources/gameover.ccbi",
		FightForce_ccbi : ccbi_dir + "/ccbi/ccbResources/decisiveBattle.ccbi",
		HeroDetail_ccbi : ccbi_dir + "/ccbi/ccbResources/HeroDetailView.ccbi",
		FriendView_ccbi : ccbi_dir + "/ccbi/ccbResources/FriendView.ccbi",
		FriendViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/FriendViewCell.ccbi",
		LeaveMessage_ccbi :ccbi_dir + "/ccbi/ccbResources/LeaveMessage.ccbi",
		LogueTownView_ccbi :ccbi_dir + "/ccbi/ccbResources/LogueTownView.ccbi",
		ItemsView_ccbi : ccbi_dir + "/ccbi/ccbResources/ItemsView.ccbi",
		RecruitView_ccbi : ccbi_dir + "/ccbi/ccbResources/RecruitView.ccbi",
		RecruitHeroesView_ccbi : ccbi_dir + "/ccbi/ccbResources/RecruitHeroesView.ccbi",
		GiftBagView_ccbi : ccbi_dir + "/ccbi/ccbResources/GiftBagView.ccbi",
		ItemTableCell_ccbi : ccbi_dir + "/ccbi/ccbResources/ItemTableCell.ccbi",
		GiftBagTableCell_ccbi : ccbi_dir + "/ccbi/ccbResources/GiftBagTableCell.ccbi",
		StageTalkView_ccbi : ccbi_dir + "/ccbi/ccbResources/StageTalkView.ccbi",
		SkillDetail_ccbi : ccbi_dir + "/ccbi/ccbResources/SkillDetailInfoView2.ccbi",
		EquipChangeSelect_ccbi : ccbi_dir + "/ccbi/ccbResources/EquipChangeSeclectView.ccbi",
		EquipDetail_ccbi : ccbi_dir + "/ccbi/ccbResources/EquipInfoView.ccbi",
		RecruitHeroesCell_ccbi :ccbi_dir + "/ccbi/ccbResources/RecruitHeroesCell.ccbi",
		ShadowGetPopUp_ccbi : ccbi_dir + "/ccbi/ccbResources/ShadowGetPopUp.ccbi",
		shadowPopup_ccbi : ccbi_dir + "/ccbi/ccbResources/shadowPopup.ccbi",
		ShadowChangeCell_ccbi : ccbi_dir + "/ccbi/ccbResources/ShadowChangeCell.ccbi",
		ShadowChangeView_ccbi : ccbi_dir + "/ccbi/ccbResources/ShadowChangeView.ccbi",
		ChapterView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChapterView.ccbi",
		ChaptersCell_ccbi : ccbi_dir + "/ccbi/ccbResources/ChaptersCell.ccbi",
		ChaptersView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChaptersView.ccbi",
		ChapterRobView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChapterRobView.ccbi",
		ChapterInfoView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChapterInfoView.ccbi",
		ChapterSaleView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChapterSaleView.ccbi",
		ChapterRobFailView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChapterRobFailView.ccbi",
		ChapterRobSuccView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChapterRobSuccView.ccbi",
		ChapterDetailInfoView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChapterDetailInfoView.ccbi",
		ChapterDetailInfoCellView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChapterDetailInfoCellView.ccbi",
		ArenaView_ccbi : ccbi_dir + "/ccbi/ccbResources/ArenaView.ccbi",
		ArenaInfoCell_ccbi : ccbi_dir + "/ccbi/ccbResources/ArenaInfoCell.ccbi",
		ArenaEnemyCell_ccbi : ccbi_dir + "/ccbi/ccbResources/ArenaEnemyCell.ccbi",
		ArenaAwardCell_ccbi : ccbi_dir + "/ccbi/ccbResources/ArenaAwardCell.ccbi",
		ArenaMenu_ccbi : ccbi_dir + "/ccbi/ccbResources/ArenaMenu.ccbi",
		LeaveMessage_ccbi : ccbi_dir + "/ccbi/ccbResources/LeaveMessage.ccbi",
		DailyMerman_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyMermanView.ccbi",
		Treaure_ccbi : ccbi_dir + "/ccbi/ccbResources/TreasureFirstView.ccbi",
		DailyDrinkView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyDrinkWineView.ccbi",
		DailyChoseHeroView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyDrinkChoseHeroView.ccbi",
		InstructSelectHeroView_ccbi : ccbi_dir + "/ccbi/ccbResources/InstructSelectHeroView.ccbi",
		InstructSelectHeroCell_ccbi : ccbi_dir + "/ccbi/ccbResources/InstructSelectHeroCellNew.ccbi",
		DailyExchangeCapView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyDrinkCapExchangeView.ccbi",
		DailyChoseHeroViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyDrinkChoseHeroCell.ccbi",
		DailyCapExchangeCell_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyDrinkCapExchangeCell.ccbi",
		UnionMain_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionMainView.ccbi",
		UnionGuide_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionOuterLayer.ccbi",
		UnionCreate_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionCreateLayer.ccbi",
		UnionHome_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionInnerLayer.ccbi",
		UnionJoin_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionJoinLayer.ccbi",
		UnionRankCell_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionRankTableCell.ccbi",
		UnionJoinInfo_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionJoinInfoLayer.ccbi",
		UnionInfo_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionInfoView.ccbi",
		UnionMemberCell_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionRankMemberInfoCellView.ccbi",
		UnionManage_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionManageLayer.ccbi",
		UnionApplicantCell_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionApplicantCell.ccbi",
		UnionAcceptMember_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionAcceptLayer.ccbi",
		UnionMember_ccbi : ccbi_dir + "/ccbi/ccbResources/unionMemberLayer.ccbi",
		UnionMemberManageCell_ccbi : ccbi_dir + "/ccbi/ccbResources/unionMemberCell.ccbi",
		UnionQuit_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionConfirm.ccbi",
		UnionMemberManageMenu_ccbi : ccbi_dir + "/ccbi/ccbResources/unionMemberMenu.ccbi",
		UnionRank_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionRankView.ccbi",
		UnionMessage_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionInformationView.ccbi",
		UnionBuild_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionUpgrateLayer.ccbi",
		UnionContribution_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionContributionPopUp.ccbi",
		UnionCandy_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionCandyLayer.ccbi",
		UnionDistributeCell_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionDistributeCell.ccbi",
		UnionDonate_ccbi : ccbi_dir + "/ccbi/ccbResources/unionJuanXianLayer.ccbi",
		UnionShop_ccbi : ccbi_dir + "/ccbi/ccbResources/unionShopViewLayer.ccbi",
		UnionShopCell_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionShopTableViewCell.ccbi",
		UnionShopPre_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionGiftRefreshPreviewPopUp.ccbi",
		UnionShopPreCell_ccbi : ccbi_dir + "/ccbi/ccbResources/UnionGiftPreviewCell.ccbi",
		ChatView_ccbi : ccbi_dir + "/ccbi/ccbResources/ChatView.ccbi",
		SystemSettingView_ccbi : ccbi_dir + "/ccbi/ccbResources/SystemSettingView.ccbi",
		SystemSettingViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/SystemSettingViewCell.ccbi",
		LoginServerView_ccbi : ccbi_dir + "/ccbi/ccbResources/LoginServerView.ccbi",
		ShopChargePopUp_ccbi : ccbi_dir + "/ccbi/ccbResources/ShopChargePopUp.ccbi",
		ShopRechargeTopCell_ccbi : ccbi_dir + "/ccbi/ccbResources/ShopRechargeTopCell.ccbi",
		ShopRechargeBottomCell_ccbi : ccbi_dir + "/ccbi/ccbResources/ShopRechargeBottomCell.ccbi",
		QuestLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/QuestLayer.ccbi",
		QuestCell_ccbi : ccbi_dir + "/ccbi/ccbResources/QuestCell.ccbi",
		QuestPopup_ccbi : ccbi_dir + "/ccbi/ccbResources/QuestPopup.ccbi",
		CommonHelp_ccbi : ccbi_dir + "/ccbi/ccbResources/CommonHelpView.ccbi",
		StageLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/StageView.ccbi",
		StageWin_ccbi : ccbi_dir + "/ccbi/ccbResources/SailWinView.ccbi",
		StageLost_ccbi : ccbi_dir + "/ccbi/ccbResources/SailLoseView.ccbi",
		NewWorldWin_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldWinView.ccbi",
		NewWorldLose_ccbi : ccbi_dir + "/ccbi/ccbResources/NewWorldLoseView.ccbi",
		MultiFightResult_ccbi : ccbi_dir + "/ccbi/ccbResources/SweepInfoView.ccbi",
		MultiFightResultCell_ccbi : ccbi_dir + "/ccbi/ccbResources/SweepCellView.ccbi",
		InstructHeroSView_ccbi : ccbi_dir + "/ccbi/ccbResources/InstructHeroSView.ccbi",
		InstructHeroCellView_ccbi : ccbi_dir + "/ccbi/ccbResources/InstructHeroCellView.ccbi",
		InstructHeroGView_ccbi : ccbi_dir + "/ccbi/ccbResources/InstructHeroGView.ccbi",
		InstructSingleCDView_ccbi : ccbi_dir + "/ccbi/ccbResources/InstructSingleCDView.ccbi",
		InstructSingleResultInfoView_ccbi : ccbi_dir + "/ccbi/ccbResources/InstructSingleResultInfoView.ccbi",
		InstructGroupResultInfoView_ccbi : ccbi_dir + "/ccbi/ccbResources/InstructGroupResultInfoView.ccbi",
	    LoginUpdate_ccbi : ccbi_dir + "/ccbi/ccbResources/LoginUpdateView.ccbi",
	    AnnounceLayerView_ccbi : ccbi_dir + "/ccbi/ccbResources/AnnounceLayerView.ccbi",
	    Feedback_ccbi : ccbi_dir + "/ccbi/ccbResources/Feedback.ccbi",
	    Cdkey_ccbi : ccbi_dir + "/ccbi/ccbResources/Cdkey.ccbi",
	    Cusservice_ccbi : ccbi_dir + "/ccbi/ccbResources/Cusservice.ccbi",
	    CusserviceCell_ccbi :ccbi_dir + "/ccbi/ccbResources/CusserviceCell.ccbi",
	    SkillChangeSelect_ccbi : ccbi_dir + "/ccbi/ccbResources/SkillChangeSelectView.ccbi",
	    HelpView_ccbi : ccbi_dir + "/ccbi/ccbResources/HelpView.ccbi",
	    HelpCell_ccbi : ccbi_dir + "/ccbi/ccbResources/HelpCell.ccbi",
	    AddFriendLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/AddFriendLayer.ccbi",
		AddFriendViewCell_ccbi : ccbi_dir + "/ccbi/ccbResources/AddFriendViewCell.ccbi",
		DailySignInCell_ccbi : ccbi_dir + "/ccbi/ccbResources/DailySignInCell.ccbi",
		DailySignInPopUpView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailySignInPopUpView.ccbi",
		MultiItemCell_ccbi : ccbi_dir + "/ccbi/ccbResources/MultiItemCell.ccbi",
		GetInvitePopUp_ccbi : ccbi_dir + "/ccbi/ccbResources/GetInvitePopUp.ccbi",
		GetSomeBigRewardCell_ccbi : ccbi_dir + "/ccbi/ccbResources/GetSomeBigRewardCell.ccbi",
		DailyLevelUpAward_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyLevelUpAward.ccbi",
		LevelUpdateAwardTopDespCell_ccbi : ccbi_dir + "/ccbi/ccbResources/LevelUpdateAwardTopDespCell.ccbi",
		LevelUpdateAwardCell_ccbi : ccbi_dir + "/ccbi/ccbResources/LevelUpdateAwardCell.ccbi",
		DailyDecomposeAndComposeView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyDecomposeAndComposeView.ccbi",
		DailyDecomposeChooseCell_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyDecomposeChooseCell.ccbi",
		DailyDrinkChoseHeroView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyDrinkChoseHeroView.ccbi",
		HandBookEquipCell_ccbi : ccbi_dir + "/ccbi/ccbResources/HandBookEquipCell.ccbi",
		DailyDecomposeChooseCell_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyDecomposeChooseCell.ccbi",
		DialyMermanAnimationView_ccbi : ccbi_dir + "/ccbi/ccbResources/DialyMermanAnimationView.ccbi",
		DailyDecomposeCheckView_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyDecomposeCheckView.ccbi",
		DailyMothCardCell_ccbi : ccbi_dir + "/ccbi/ccbResources/DailyMothCardCell.ccbi",
		OLGuideView_ccbi : ccbi_dir + "/ccbi/ccbResources/OLGuideView.ccbi",
		FriendOptionLayer_ccbi : ccbi_dir + "/ccbi/ccbResources/FriendOptionLayer.ccbi",
		SelectRoleView_ccbi : ccbi_dir + "/ccbi/ccbResources/SelectRoleView.ccbi",
		CreateNameView_ccbi : ccbi_dir + "/ccbi/ccbResources/CreateNameView.ccbi",
		GuideView_ccbi : ccbi_dir + "/ccbi/ccbResources/GuideView.ccbi",
		
		TitleInfoView_ccbi : ccbi_dir + "/ccbi/ccbResources/TitleInfoView.ccbi",
		TitleInfoCellView_ccbi : ccbi_dir + "/ccbi/ccbResources/TitleInfoCellView.ccbi",
		AllTitleInfoView_ccbi : ccbi_dir + "/ccbi/ccbResources/AllTitleInfoView.ccbi",
		TitleBottomTableCell_ccbi : ccbi_dir + "/ccbi/ccbResources/TitleBottomTableCell.ccbi",
}
var g_resources = [];
for (var k in ccbi_res) {
	g_resources.push(ccbi_dir[k]);
}

cc.BuilderReader.setResourcePath(ccbi_dir + "/ccbi/");