--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
Layer:setLocalZOrder(0)

--Create Panel
local Panel = ccui.Layout:create()
Panel:ignoreContentAdaptWithSize(false)

Panel:setClippingEnabled(false)
Panel:setBackGroundImageCapInsets(cc.rect(0,0,0,0))
Panel:setBackGroundColor(cc.c3b(150, 200, 255))
Panel:setBackGroundColor(cc.c3b(150, 200, 255),cc.c3b(255, 255, 255))
Panel:setBackGroundColorVector(cc.p(0,1))
Panel:setBackGroundColorType(1)
Panel:setBackGroundColorOpacity(0)
Panel:setBackGroundImageScale9Enabled(false)

Panel:setTouchEnabled(true)
Panel:setLayoutComponentEnabled(true)
Panel:setName("Panel")
Panel:setLocalZOrder(0)
Panel:setTag(12)
Panel:setCascadeColorEnabled(true)
Panel:setCascadeOpacityEnabled(true)
Panel:setVisible(true)
Panel:setAnchorPoint(0.5, 0.5)
Panel:setPosition(540, 360)
Panel:setScaleX(1)
Panel:setScaleY(1)
Panel:setRotation(0)
Panel:setRotationSkewX(0)
Panel:setRotationSkewY(0)
Panel:setOpacity(255)
Panel:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Panel)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.1852)
layout:setPercentHeight(0.2778)

layout:setSize(cc.size(200, 200))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(440)
layout:setRightMargin(440)
layout:setTopMargin(260)
layout:setBottomMargin(260)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Layer:addChild(Panel)

--Create left
cc.SpriteFrameCache:getInstance():addSpriteFrames("olympic/res/olympic.plist")
local left = cc.Sprite:createWithSpriteFrameName("olympic/res/22.png")
left:setName("left")
left:setLocalZOrder(0)
left:setTag(50)
left:setCascadeColorEnabled(true)
left:setCascadeOpacityEnabled(true)
left:setVisible(true)
left:setAnchorPoint(0.5, 0.5)
left:setPosition(-250, 28)
left:setScaleX(1)
left:setScaleY(1)
left:setRotation(0)
left:setRotationSkewX(0)
left:setRotationSkewY(0)
left:setOpacity(255)
left:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(left)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(-1.25)
layout:setPositionPercentY(0.14)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(336, 529))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-418)
layout:setRightMargin(282)
layout:setTopMargin(-92.5)
layout:setBottomMargin(-236.5)
left:setFlippedX(false)
left:setFlippedY(false)
Panel:addChild(left)

--Create due
local due = ccui.Text:create()
due:ignoreContentAdaptWithSize(true)
due:setTextAreaSize(cc.size(0, 0))
due:setFontName("Resources/font/ttf/black_body_2.TTF")
due:setFontSize(22)
due:setString([[兑换截止日期：2016-10-11]])
due:setTextHorizontalAlignment(0)
due:setTextVerticalAlignment(0)
due:setTouchScaleChangeEnabled(false)
due:setFlippedX(false)
due:setFlippedY(false)
due:enableShadow(cc.c4b(0, 0, 0, 255), cc.size(2, -2), 0)
due:setTouchEnabled(false)
due:setLayoutComponentEnabled(true)
due:setName("due")
due:setLocalZOrder(0)
due:setTag(21)
due:setCascadeColorEnabled(true)
due:setCascadeOpacityEnabled(true)
due:setVisible(true)
due:setAnchorPoint(0.5, 0.5)
due:setPosition(168.5, 496)
due:setScaleX(1)
due:setScaleY(1)
due:setRotation(0)
due:setRotationSkewX(0)
due:setRotationSkewY(0)
due:setOpacity(255)
due:setColor(cc.c3b(255, 255, 0))
layout = ccui.LayoutComponent:bindLayoutComponent(due)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5015)
layout:setPositionPercentY(0.9376)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(286, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(25.5)
layout:setRightMargin(24.5)
layout:setTopMargin(20.5)
layout:setBottomMargin(483.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
left:addChild(due)

--Create listBG
local listBG = ccui.ImageView:create()
listBG:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("olympic/res/olympic.plist")
listBG:loadTexture("olympic/res/23.png",1)

listBG:setFlippedX(false)
listBG:setFlippedY(false)

listBG:setScale9Enabled(true)
listBG:setCapInsets(cc.rect(228,174,236,181))
listBG:setTouchEnabled(false)
listBG:setLayoutComponentEnabled(true)
listBG:setName("listBG")
listBG:setLocalZOrder(0)
listBG:setTag(52)
listBG:setCascadeColorEnabled(true)
listBG:setCascadeOpacityEnabled(true)
listBG:setVisible(true)
listBG:setAnchorPoint(0.5, 0.5)
listBG:setPosition(272.5926, 27)
listBG:setScaleX(1)
listBG:setScaleY(1)
listBG:setRotation(0)
listBG:setRotationSkewX(0)
listBG:setRotationSkewY(0)
listBG:setOpacity(255)
listBG:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(listBG)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(1.363)
layout:setPositionPercentY(0.135)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.6407)
layout:setPercentHeight(0.7347)

layout:setSize(cc.size(692, 529))

layout:setHorizontalEdge(3)
layout:setVerticalEdge(0)
layout:setLeftMargin(-73.4074)
layout:setRightMargin(-418.5926)
layout:setTopMargin(-91.5)
layout:setBottomMargin(-237.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Panel:addChild(listBG)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

