--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create win
local win = ccui.ImageView:create()
win:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("server_exercise/res/serverexerise.plist")
win:loadTexture("server_exercise/res/21.png",1)

win:setFlippedX(false)
win:setFlippedY(false)

win:setScale9Enabled(false)
win:setCapInsets(cc.rect(0,0,73,73))
win:setTouchEnabled(false)
win:setLayoutComponentEnabled(true)
win:setName("win")
win:setLocalZOrder(0)
win:setTag(84)
win:setCascadeColorEnabled(true)
win:setCascadeOpacityEnabled(true)
win:setVisible(true)
win:setAnchorPoint(0.5, 0.5)
win:setPosition(52, 42)
win:setScaleX(0.8)
win:setScaleY(0.8)
win:setRotation(0)
win:setRotationSkewX(0)
win:setRotationSkewY(0)
win:setOpacity(255)
win:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(win)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(73, 73))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(15.5)
layout:setRightMargin(-88.5)
layout:setTopMargin(-78.5)
layout:setBottomMargin(5.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(win)

--Create lost
local lost = ccui.ImageView:create()
lost:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("server_exercise/res/serverexerise.plist")
lost:loadTexture("server_exercise/res/22.png",1)

lost:setFlippedX(false)
lost:setFlippedY(false)

lost:setScale9Enabled(false)
lost:setCapInsets(cc.rect(0,0,73,73))
lost:setTouchEnabled(false)
lost:setLayoutComponentEnabled(true)
lost:setName("lost")
lost:setLocalZOrder(0)
lost:setTag(85)
lost:setCascadeColorEnabled(true)
lost:setCascadeOpacityEnabled(true)
lost:setVisible(true)
lost:setAnchorPoint(0.5, 0.5)
lost:setPosition(52.0003, 42.0001)
lost:setScaleX(0.8)
lost:setScaleY(0.8)
lost:setRotation(0)
lost:setRotationSkewX(0)
lost:setRotationSkewY(0)
lost:setOpacity(255)
lost:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(lost)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(73, 73))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(15.5003)
layout:setRightMargin(-88.5003)
layout:setTopMargin(-78.5001)
layout:setBottomMargin(5.5001)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(lost)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

