--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("service_legion_war/res/di-5.png",0)

bg:setFlippedX(false)
bg:setFlippedY(false)

bg:setScale9Enabled(true)
bg:setCapInsets(cc.rect(112,35,90,38))
bg:setTouchEnabled(false)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setLocalZOrder(0)
bg:setTag(19)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setVisible(true)
bg:setAnchorPoint(0.5, 0.5)
bg:setPosition(474.0406, 58.3984)
bg:setScaleX(1)
bg:setScaleY(1)
bg:setRotation(0)
bg:setRotationSkewX(0)
bg:setRotationSkewY(0)
bg:setOpacity(255)
bg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(940, 120))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(4.0406)
layout:setRightMargin(-944.0406)
layout:setTopMargin(-118.3984)
layout:setBottomMargin(-1.6016)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(bg)

--Create Text
local Text = ccui.Text:create()
Text:ignoreContentAdaptWithSize(false)
Text:setFontName("Resources/font/ttf/black_body.TTF")
Text:setFontSize(22)
Text:setString([[我们军团的一个牛逼玩家打败了对面的二愣子啊是谁啊，我也不知道，反正获得了好多东西]])
Text:setTextHorizontalAlignment(0)
Text:setTextVerticalAlignment(0)
Text:setTouchScaleChangeEnabled(false)
Text:setFlippedX(false)
Text:setFlippedY(false)
Text:setTouchEnabled(false)
Text:setLayoutComponentEnabled(true)
Text:setName("Text")
Text:setLocalZOrder(0)
Text:setTag(20)
Text:setCascadeColorEnabled(true)
Text:setCascadeOpacityEnabled(true)
Text:setVisible(true)
Text:setAnchorPoint(0.5, 0.5)
Text:setPosition(347.466, 59.746)
Text:setScaleX(1)
Text:setScaleY(1)
Text:setRotation(0)
Text:setRotationSkewX(0)
Text:setRotationSkewY(0)
Text:setOpacity(255)
Text:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Text)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.3696)
layout:setPositionPercentY(0.4979)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.6667)
layout:setPercentHeight(0.6667)

layout:setSize(cc.size(600, 80))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(47.466)
layout:setRightMargin(292.534)
layout:setTopMargin(20.254)
layout:setBottomMargin(19.746)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(Text)

--Create CheckBt
local CheckBt = ccui.Button:create()
CheckBt:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
CheckBt:loadTextureNormal("Resources/common/button/btn_3.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
CheckBt:loadTexturePressed("Resources/common/button/anniuhong02.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
CheckBt:loadTextureDisabled("Resources/common/button/anniuhong02.png",1)
CheckBt:setTitleFontSize(14)
CheckBt:setTitleText("")
CheckBt:setTitleColor(cc.c3b(65, 65, 70))
CheckBt:setFlippedX(false)
CheckBt:setFlippedY(false)
CheckBt:setScale9Enabled(true)
CheckBt:setCapInsets(cc.rect(15,11,122,44))
CheckBt:setBright(true)
CheckBt:setTouchEnabled(true)
CheckBt:setLayoutComponentEnabled(true)
CheckBt:setName("CheckBt")
CheckBt:setLocalZOrder(0)
CheckBt:setTag(21)
CheckBt:setCascadeColorEnabled(true)
CheckBt:setCascadeOpacityEnabled(true)
CheckBt:setVisible(true)
CheckBt:setAnchorPoint(0.5, 0.5)
CheckBt:setPosition(826.5052, 64.0448)
CheckBt:setScaleX(1)
CheckBt:setScaleY(1)
CheckBt:setRotation(0)
CheckBt:setRotationSkewX(0)
CheckBt:setRotationSkewY(0)
CheckBt:setOpacity(255)
CheckBt:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBt)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.8793)
layout:setPositionPercentY(0.5337)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.18)
layout:setPercentHeight(0.5667)

layout:setSize(cc.size(162, 68))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(745.5052)
layout:setRightMargin(32.4948)
layout:setTopMargin(21.9552)
layout:setBottomMargin(30.0448)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(CheckBt)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("service_legion_war/res/main.plist")
Image_2:loadTexture("service_legion_war/res/chakan.png",1)

Image_2:setFlippedX(false)
Image_2:setFlippedY(false)

Image_2:setScale9Enabled(false)
Image_2:setCapInsets(cc.rect(0,0,109,25))
Image_2:setTouchEnabled(false)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setLocalZOrder(0)
Image_2:setTag(22)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setVisible(true)
Image_2:setAnchorPoint(0.5, 0.5)
Image_2:setPosition(82.505, 35.6454)
Image_2:setScaleX(1)
Image_2:setScaleY(1)
Image_2:setRotation(0)
Image_2:setRotationSkewX(0)
Image_2:setRotationSkewY(0)
Image_2:setOpacity(255)
Image_2:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5093)
layout:setPositionPercentY(0.5242)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.7171)
layout:setPercentHeight(0.3788)

layout:setSize(cc.size(109, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(28.005)
layout:setRightMargin(24.995)
layout:setTopMargin(19.8546)
layout:setBottomMargin(23.1454)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
CheckBt:addChild(Image_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

