--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create Img
local Img = ccui.ImageView:create()
Img:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("inter_service_escort/res/res.plist")
Img:loadTexture("inter_service_escort/res/1.png",1)

Img:setFlippedX(false)
Img:setFlippedY(false)

Img:setScale9Enabled(false)
Img:setCapInsets(cc.rect(0,0,113,113))
Img:setTouchEnabled(false)
Img:setLayoutComponentEnabled(true)
Img:setName("Img")
Img:setLocalZOrder(0)
Img:setTag(64)
Img:setCascadeColorEnabled(true)
Img:setCascadeOpacityEnabled(true)
Img:setVisible(true)
Img:setAnchorPoint(0.5, 0.5)
Img:setPosition(71.9999, 96.9984)
Img:setScaleX(1)
Img:setScaleY(1)
Img:setRotation(0)
Img:setRotationSkewX(0)
Img:setRotationSkewY(0)
Img:setOpacity(255)
Img:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Img)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(113, 113))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(15.4999)
layout:setRightMargin(-128.4999)
layout:setTopMargin(-153.4984)
layout:setBottomMargin(40.4984)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Img)

--Create Name
local Name = ccui.Text:create()
Name:ignoreContentAdaptWithSize(true)
Name:setTextAreaSize(cc.size(0, 0))
Name:setFontName("Resources/font/ttf/black_body_2.TTF")
Name:setFontSize(20)
Name:setString([[黑麦面包]])
Name:setTextHorizontalAlignment(0)
Name:setTextVerticalAlignment(0)
Name:setTouchScaleChangeEnabled(false)
Name:setFlippedX(false)
Name:setFlippedY(false)
Name:enableOutline(cc.c4b(0, 0, 0, 255), 1)
Name:setTouchEnabled(false)
Name:setLayoutComponentEnabled(true)
Name:setName("Name")
Name:setLocalZOrder(0)
Name:setTag(65)
Name:setCascadeColorEnabled(true)
Name:setCascadeOpacityEnabled(true)
Name:setVisible(true)
Name:setAnchorPoint(0.5, 0.5)
Name:setPosition(73, 30.9974)
Name:setScaleX(1)
Name:setScaleY(1)
Name:setRotation(0)
Name:setRotationSkewX(0)
Name:setRotationSkewY(0)
Name:setOpacity(255)
Name:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Name)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(82, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(32)
layout:setRightMargin(-114)
layout:setTopMargin(-43.4974)
layout:setBottomMargin(18.4974)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Name)

--Create Choose
local Choose = ccui.ImageView:create()
Choose:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("inter_service_escort/res/res.plist")
Choose:loadTexture("inter_service_escort/res/xuanze1.png",1)

Choose:setFlippedX(false)
Choose:setFlippedY(false)

Choose:setScale9Enabled(false)
Choose:setCapInsets(cc.rect(0,0,117,117))
Choose:setTouchEnabled(false)
Choose:setLayoutComponentEnabled(true)
Choose:setName("Choose")
Choose:setLocalZOrder(0)
Choose:setTag(124)
Choose:setCascadeColorEnabled(true)
Choose:setCascadeOpacityEnabled(true)
Choose:setVisible(true)
Choose:setAnchorPoint(0.5, 0.5)
Choose:setPosition(71.9999, 97.9983)
Choose:setScaleX(1)
Choose:setScaleY(1)
Choose:setRotation(0)
Choose:setRotationSkewX(0)
Choose:setRotationSkewY(0)
Choose:setOpacity(255)
Choose:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Choose)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(117, 117))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(13.4999)
layout:setRightMargin(-130.4999)
layout:setTopMargin(-156.4983)
layout:setBottomMargin(39.4983)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Choose)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

