--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
Layer:setLocalZOrder(0)

--Create panel
local panel = ccui.Layout:create()
panel:ignoreContentAdaptWithSize(false)

panel:setClippingEnabled(false)
panel:setBackGroundImageCapInsets(cc.rect(0,0,0,0))
panel:setBackGroundColor(cc.c3b(150, 200, 255))
panel:setBackGroundColor(cc.c3b(150, 200, 255),cc.c3b(255, 255, 255))
panel:setBackGroundColorVector(cc.p(0,1))
panel:setBackGroundColorType(1)
panel:setBackGroundColorOpacity(102)
panel:setBackGroundImageScale9Enabled(false)

panel:setTouchEnabled(true)
panel:setLayoutComponentEnabled(true)
panel:setName("panel")
panel:setLocalZOrder(0)
panel:setTag(119)
panel:setCascadeColorEnabled(true)
panel:setCascadeOpacityEnabled(true)
panel:setVisible(true)
panel:setAnchorPoint(0.5, 0.5)
panel:setPosition(540, 360)
panel:setScaleX(1)
panel:setScaleY(1)
panel:setRotation(0)
panel:setRotationSkewX(0)
panel:setRotationSkewY(0)
panel:setOpacity(255)
panel:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(panel)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.1852)
layout:setPercentHeight(0.2778)

layout:setSize(cc.size(200, 200))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(440)
layout:setRightMargin(440)
layout:setTopMargin(260)
layout:setBottomMargin(260)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Layer:addChild(panel)

--Create jiangliyulan_4
local jiangliyulan_4 = cc.Sprite:create("torch/res/jiangliyulan.jpg")
jiangliyulan_4:setName("jiangliyulan_4")
jiangliyulan_4:setLocalZOrder(0)
jiangliyulan_4:setTag(126)
jiangliyulan_4:setCascadeColorEnabled(true)
jiangliyulan_4:setCascadeOpacityEnabled(true)
jiangliyulan_4:setVisible(true)
jiangliyulan_4:setAnchorPoint(0.5, 0.5)
jiangliyulan_4:setPosition(100, 100)
jiangliyulan_4:setScaleX(1)
jiangliyulan_4:setScaleY(1)
jiangliyulan_4:setRotation(0)
jiangliyulan_4:setRotationSkewX(0)
jiangliyulan_4:setRotationSkewY(0)
jiangliyulan_4:setOpacity(255)
jiangliyulan_4:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(jiangliyulan_4)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(459, 475))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-129.5)
layout:setRightMargin(-129.5)
layout:setTopMargin(-137.5)
layout:setBottomMargin(-137.5)
jiangliyulan_4:setFlippedX(false)
jiangliyulan_4:setFlippedY(false)
panel:addChild(jiangliyulan_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

