--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create Img_stage_icon
local Img_stage_icon = ccui.ImageView:create()
Img_stage_icon:ignoreContentAdaptWithSize(false)
Img_stage_icon:loadTexture("inter_service_arena/res/stage_icon_3.png",0)

Img_stage_icon:setFlippedX(false)
Img_stage_icon:setFlippedY(false)

Img_stage_icon:setScale9Enabled(false)
Img_stage_icon:setCapInsets(cc.rect(0,0,110,93))
Img_stage_icon:setTouchEnabled(false)
Img_stage_icon:setLayoutComponentEnabled(true)
Img_stage_icon:setName("Img_stage_icon")
Img_stage_icon:setLocalZOrder(0)
Img_stage_icon:setTag(219)
Img_stage_icon:setCascadeColorEnabled(true)
Img_stage_icon:setCascadeOpacityEnabled(true)
Img_stage_icon:setVisible(true)
Img_stage_icon:setAnchorPoint(0.5, 0.5)
Img_stage_icon:setPosition(83.3777, 65.3559)
Img_stage_icon:setScaleX(1)
Img_stage_icon:setScaleY(1)
Img_stage_icon:setRotation(0)
Img_stage_icon:setRotationSkewX(0)
Img_stage_icon:setRotationSkewY(0)
Img_stage_icon:setOpacity(255)
Img_stage_icon:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Img_stage_icon)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(110, 93))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(28.3777)
layout:setRightMargin(-138.3777)
layout:setTopMargin(-111.8559)
layout:setBottomMargin(18.8559)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Img_stage_icon)

--Create Img_stage_name
local Img_stage_name = ccui.ImageView:create()
Img_stage_name:ignoreContentAdaptWithSize(false)
Img_stage_name:loadTexture("inter_service_arena/res/stage_name2_3.png",0)

Img_stage_name:setFlippedX(false)
Img_stage_name:setFlippedY(false)

Img_stage_name:setScale9Enabled(false)
Img_stage_name:setCapInsets(cc.rect(0,0,96,25))
Img_stage_name:setTouchEnabled(false)
Img_stage_name:setLayoutComponentEnabled(true)
Img_stage_name:setName("Img_stage_name")
Img_stage_name:setLocalZOrder(0)
Img_stage_name:setTag(223)
Img_stage_name:setCascadeColorEnabled(true)
Img_stage_name:setCascadeOpacityEnabled(true)
Img_stage_name:setVisible(true)
Img_stage_name:setAnchorPoint(0.5, 0.5)
Img_stage_name:setPosition(39, 18.5105)
Img_stage_name:setScaleX(1)
Img_stage_name:setScaleY(1)
Img_stage_name:setRotation(0)
Img_stage_name:setRotationSkewX(0)
Img_stage_name:setRotationSkewY(0)
Img_stage_name:setOpacity(255)
Img_stage_name:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Img_stage_name)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.3545)
layout:setPositionPercentY(0.199)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.8727)
layout:setPercentHeight(0.2688)

layout:setSize(cc.size(96, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-9)
layout:setRightMargin(23)
layout:setTopMargin(61.9895)
layout:setBottomMargin(6.0105)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Img_stage_icon:addChild(Img_stage_name)

--Create Img_stage_num
local Img_stage_num = ccui.ImageView:create()
Img_stage_num:ignoreContentAdaptWithSize(false)
Img_stage_num:loadTexture("inter_service_arena/res/stage_num2_3.png",0)

Img_stage_num:setFlippedX(false)
Img_stage_num:setFlippedY(false)

Img_stage_num:setScale9Enabled(false)
Img_stage_num:setCapInsets(cc.rect(0,0,34,20))
Img_stage_num:setTouchEnabled(false)
Img_stage_num:setLayoutComponentEnabled(true)
Img_stage_num:setName("Img_stage_num")
Img_stage_num:setLocalZOrder(0)
Img_stage_num:setTag(224)
Img_stage_num:setCascadeColorEnabled(true)
Img_stage_num:setCascadeOpacityEnabled(true)
Img_stage_num:setVisible(true)
Img_stage_num:setAnchorPoint(0.5, 0.5)
Img_stage_num:setPosition(103.8663, 17.3105)
Img_stage_num:setScaleX(1)
Img_stage_num:setScaleY(1)
Img_stage_num:setRotation(0)
Img_stage_num:setRotationSkewX(0)
Img_stage_num:setRotationSkewY(0)
Img_stage_num:setOpacity(255)
Img_stage_num:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Img_stage_num)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.9442)
layout:setPositionPercentY(0.1861)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.3091)
layout:setPercentHeight(0.2151)

layout:setSize(cc.size(34, 20))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(86.8663)
layout:setRightMargin(-10.8663)
layout:setTopMargin(65.6895)
layout:setBottomMargin(7.3105)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Img_stage_icon:addChild(Img_stage_num)

--Create Node_2
local Node_2=cc.Node:create()
Node_2:setName("Node_2")
Node_2:setLocalZOrder(0)
Node_2:setTag(220)
Node_2:setCascadeColorEnabled(true)
Node_2:setCascadeOpacityEnabled(true)
Node_2:setVisible(true)
Node_2:setAnchorPoint(0, 0)
Node_2:setPosition(591.266, 11.9998)
Node_2:setScaleX(1)
Node_2:setScaleY(1)
Node_2:setRotation(0)
Node_2:setRotationSkewX(0)
Node_2:setRotationSkewY(0)
Node_2:setOpacity(255)
Node_2:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Node_2)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(591.266)
layout:setRightMargin(-591.266)
layout:setTopMargin(-11.9998)
layout:setBottomMargin(11.9998)
Node:addChild(Node_2)

--Create Node_1
local Node_1=cc.Node:create()
Node_1:setName("Node_1")
Node_1:setLocalZOrder(0)
Node_1:setTag(221)
Node_1:setCascadeColorEnabled(true)
Node_1:setCascadeOpacityEnabled(true)
Node_1:setVisible(true)
Node_1:setAnchorPoint(0, 0)
Node_1:setPosition(217.7778, 11.9998)
Node_1:setScaleX(1)
Node_1:setScaleY(1)
Node_1:setRotation(0)
Node_1:setRotationSkewX(0)
Node_1:setRotationSkewY(0)
Node_1:setOpacity(255)
Node_1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Node_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(217.7778)
layout:setRightMargin(-217.7778)
layout:setTopMargin(-11.9998)
layout:setBottomMargin(11.9998)
Node:addChild(Node_1)

--Create Image_1_0
local Image_1_0 = ccui.ImageView:create()
Image_1_0:ignoreContentAdaptWithSize(false)
Image_1_0:loadTexture("inter_service_arena/res/fengexian.png",0)

Image_1_0:setFlippedX(false)
Image_1_0:setFlippedY(false)

Image_1_0:setScale9Enabled(true)
Image_1_0:setCapInsets(cc.rect(31,1,34,2))
Image_1_0:setTouchEnabled(false)
Image_1_0:setLayoutComponentEnabled(true)
Image_1_0:setName("Image_1_0")
Image_1_0:setLocalZOrder(0)
Image_1_0:setTag(261)
Image_1_0:setCascadeColorEnabled(true)
Image_1_0:setCascadeOpacityEnabled(true)
Image_1_0:setVisible(true)
Image_1_0:setAnchorPoint(0.5, 0.5)
Image_1_0:setPosition(479.5111, 5.3)
Image_1_0:setScaleX(1)
Image_1_0:setScaleY(1)
Image_1_0:setRotation(0)
Image_1_0:setRotationSkewX(0)
Image_1_0:setRotationSkewY(0)
Image_1_0:setOpacity(255)
Image_1_0:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1_0)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(960, 4))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-0.4889)
layout:setRightMargin(-959.5111)
layout:setTopMargin(-7.3)
layout:setBottomMargin(3.3)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Image_1_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

