--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("fire_rebate/res/res.plist")
bg:loadTexture("fire_rebate/res/dikuang.png",1)

bg:setFlippedX(false)
bg:setFlippedY(false)

bg:setScale9Enabled(true)
bg:setCapInsets(cc.rect(62,51,64,54))
bg:setTouchEnabled(false)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setLocalZOrder(0)
bg:setTag(66)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setVisible(true)
bg:setAnchorPoint(0, 0)
bg:setPosition(0, 0)
bg:setScaleX(1)
bg:setScaleY(1)
bg:setRotation(0)
bg:setRotationSkewX(0)
bg:setRotationSkewY(0)
bg:setOpacity(255)
bg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(228, 156))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(0)
layout:setRightMargin(-228)
layout:setTopMargin(-156)
layout:setBottomMargin(0)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(bg)

--Create Sprite_1
local Sprite_1 = cc.Sprite:create("Resources/common/icon/coin/1.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setLocalZOrder(0)
Sprite_1:setTag(47)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setVisible(true)
Sprite_1:setAnchorPoint(0.5, 0.5)
Sprite_1:setPosition(114, 78)
Sprite_1:setScaleX(0.8589)
Sprite_1:setScaleY(0.8683)
Sprite_1:setRotation(0)
Sprite_1:setRotationSkewX(0)
Sprite_1:setRotationSkewY(0)
Sprite_1:setOpacity(255)
Sprite_1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.3684)
layout:setPercentHeight(0.4615)

layout:setSize(cc.size(84, 72))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(72)
layout:setRightMargin(72)
layout:setTopMargin(42)
layout:setBottomMargin(42)
Sprite_1:setFlippedX(false)
Sprite_1:setFlippedY(false)
bg:addChild(Sprite_1)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("fire_rebate/res/res.plist")
Image_3:loadTexture("fire_rebate/res/biaoqian.png",1)

Image_3:setFlippedX(false)
Image_3:setFlippedY(false)

Image_3:setScale9Enabled(false)
Image_3:setCapInsets(cc.rect(0,0,85,85))
Image_3:setTouchEnabled(false)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setLocalZOrder(0)
Image_3:setTag(1016)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setVisible(true)
Image_3:setAnchorPoint(0.5, 0.5)
Image_3:setPosition(46.5858, 109.6253)
Image_3:setScaleX(0.9623)
Image_3:setScaleY(1.0084)
Image_3:setRotation(0)
Image_3:setRotationSkewX(0)
Image_3:setRotationSkewY(0)
Image_3:setOpacity(255)
Image_3:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.2043)
layout:setPositionPercentY(0.7027)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.3728)
layout:setPercentHeight(0.5449)

layout:setSize(cc.size(85, 85))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(4.0858)
layout:setRightMargin(138.9142)
layout:setTopMargin(3.8747)
layout:setBottomMargin(67.1253)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(Image_3)

--Create ConNum
local ConNum = ccui.Text:create()
ConNum:ignoreContentAdaptWithSize(true)
ConNum:setTextAreaSize(cc.size(0, 0))
ConNum:setFontName("Resources/font/ttf/black_body_2.TTF")
ConNum:setFontSize(20)
ConNum:setString([[Text Label]])
ConNum:setTextHorizontalAlignment(0)
ConNum:setTextVerticalAlignment(0)
ConNum:setTouchScaleChangeEnabled(false)
ConNum:setFlippedX(false)
ConNum:setFlippedY(false)
ConNum:setTouchEnabled(false)
ConNum:setLayoutComponentEnabled(true)
ConNum:setName("ConNum")
ConNum:setLocalZOrder(0)
ConNum:setTag(12)
ConNum:setCascadeColorEnabled(true)
ConNum:setCascadeOpacityEnabled(true)
ConNum:setVisible(true)
ConNum:setAnchorPoint(0.5, 0.5)
ConNum:setPosition(112.936, 34.6966)
ConNum:setScaleX(1)
ConNum:setScaleY(1)
ConNum:setRotation(0)
ConNum:setRotationSkewX(0)
ConNum:setRotationSkewY(0)
ConNum:setOpacity(255)
ConNum:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(ConNum)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.4953)
layout:setPositionPercentY(0.2224)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(101, 23))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(62.436)
layout:setRightMargin(64.564)
layout:setTopMargin(109.8034)
layout:setBottomMargin(23.1966)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(ConNum)

--Create Day
local Day = ccui.Text:create()
Day:ignoreContentAdaptWithSize(true)
Day:setTextAreaSize(cc.size(0, 0))
Day:setFontName("Resources/font/ttf/black_body_2.TTF")
Day:setFontSize(20)
Day:setString([[第几天]])
Day:setTextHorizontalAlignment(0)
Day:setTextVerticalAlignment(0)
Day:setTouchScaleChangeEnabled(false)
Day:setFlippedX(false)
Day:setFlippedY(false)
Day:setTouchEnabled(false)
Day:setLayoutComponentEnabled(true)
Day:setName("Day")
Day:setLocalZOrder(0)
Day:setTag(11)
Day:setCascadeColorEnabled(true)
Day:setCascadeOpacityEnabled(true)
Day:setVisible(true)
Day:setAnchorPoint(0.5, 0.5)
Day:setPosition(34.5554, 123.2189)
Day:setScaleX(1)
Day:setScaleY(1)
Day:setRotation(-45)
Day:setRotationSkewX(-45)
Day:setRotationSkewY(-45)
Day:setOpacity(255)
Day:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Day)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.1516)
layout:setPositionPercentY(0.7899)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(60, 23))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(4.5554)
layout:setRightMargin(163.4446)
layout:setTopMargin(21.2811)
layout:setBottomMargin(111.7189)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(Day)

--Create YiLingqu
local YiLingqu = ccui.ImageView:create()
YiLingqu:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/img/common_img.plist")
YiLingqu:loadTexture("Resources/common/img/D_12.png",1)

YiLingqu:setFlippedX(false)
YiLingqu:setFlippedY(false)

YiLingqu:setScale9Enabled(false)
YiLingqu:setCapInsets(cc.rect(0,0,146,121))
YiLingqu:setTouchEnabled(false)
YiLingqu:setLayoutComponentEnabled(true)
YiLingqu:setName("YiLingqu")
YiLingqu:setLocalZOrder(0)
YiLingqu:setTag(220)
YiLingqu:setCascadeColorEnabled(true)
YiLingqu:setCascadeOpacityEnabled(true)
YiLingqu:setVisible(false)
YiLingqu:setAnchorPoint(0.5, 0.5)
YiLingqu:setPosition(111.106, 88.9093)
YiLingqu:setScaleX(1)
YiLingqu:setScaleY(1)
YiLingqu:setRotation(0)
YiLingqu:setRotationSkewX(0)
YiLingqu:setRotationSkewY(0)
YiLingqu:setOpacity(255)
YiLingqu:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(YiLingqu)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(100, 80))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(61.106)
layout:setRightMargin(-161.106)
layout:setTopMargin(-128.9093)
layout:setBottomMargin(48.9093)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(YiLingqu)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

