--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
Layer:setLocalZOrder(0)

--Create Times
local Times = ccui.Text:create()
Times:ignoreContentAdaptWithSize(true)
Times:setTextAreaSize(cc.size(0, 0))
Times:setFontName("Resources/font/ttf/black_body_2.TTF")
Times:setFontSize(20)
Times:setString([[1000]])
Times:setTextHorizontalAlignment(0)
Times:setTextVerticalAlignment(0)
Times:setTouchScaleChangeEnabled(false)
Times:setFlippedX(false)
Times:setFlippedY(false)
Times:enableShadow(cc.c4b(0, 0, 0, 255), cc.size(1, -2), 0)
Times:setTouchEnabled(false)
Times:setLayoutComponentEnabled(true)
Times:setName("Times")
Times:setLocalZOrder(0)
Times:setTag(22)
Times:setCascadeColorEnabled(true)
Times:setCascadeOpacityEnabled(true)
Times:setVisible(true)
Times:setAnchorPoint(0, 0.5)
Times:setPosition(602.6667, 553)
Times:setScaleX(1)
Times:setScaleY(1)
Times:setRotation(0)
Times:setRotationSkewX(0)
Times:setRotationSkewY(0)
Times:setOpacity(255)
Times:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Times)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.558)
layout:setPositionPercentY(0.7681)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.2111)
layout:setPercentHeight(0.0319)

layout:setSize(cc.size(48, 23))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(602.6667)
layout:setRightMargin(429.3333)
layout:setTopMargin(155.5)
layout:setBottomMargin(541.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Layer:addChild(Times)

--Create Times_0
local Times_0 = ccui.Text:create()
Times_0:ignoreContentAdaptWithSize(true)
Times_0:setTextAreaSize(cc.size(0, 0))
Times_0:setFontName("Resources/font/ttf/black_body_2.TTF")
Times_0:setFontSize(20)
Times_0:setString([[当前累计干杯次数：]])
Times_0:setTextHorizontalAlignment(0)
Times_0:setTextVerticalAlignment(0)
Times_0:setTouchScaleChangeEnabled(false)
Times_0:setFlippedX(false)
Times_0:setFlippedY(false)
Times_0:enableShadow(cc.c4b(0, 0, 0, 255), cc.size(1, -2), 0)
Times_0:setTouchEnabled(false)
Times_0:setLayoutComponentEnabled(true)
Times_0:setName("Times_0")
Times_0:setLocalZOrder(0)
Times_0:setTag(49)
Times_0:setCascadeColorEnabled(true)
Times_0:setCascadeOpacityEnabled(true)
Times_0:setVisible(true)
Times_0:setAnchorPoint(0, 0.5)
Times_0:setPosition(430, 554)
Times_0:setScaleX(1)
Times_0:setScaleY(1)
Times_0:setRotation(0)
Times_0:setRotationSkewX(0)
Times_0:setRotationSkewY(0)
Times_0:setOpacity(255)
Times_0:setColor(cc.c3b(230, 238, 165))
layout = ccui.LayoutComponent:bindLayoutComponent(Times_0)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.3981)
layout:setPositionPercentY(0.7694)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.1667)
layout:setPercentHeight(0.0319)

layout:setSize(cc.size(180, 23))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(430)
layout:setRightMargin(470)
layout:setTopMargin(154.5)
layout:setBottomMargin(542.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Layer:addChild(Times_0)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

