--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create shuxing
local shuxing = ccui.Text:create()
shuxing:ignoreContentAdaptWithSize(true)
shuxing:setTextAreaSize(cc.size(0, 0))
shuxing:setFontName("Resources/font/ttf/black_body.TTF")
shuxing:setFontSize(22)
shuxing:setString([[命中百分比:+77%]])
shuxing:setTextHorizontalAlignment(0)
shuxing:setTextVerticalAlignment(0)
shuxing:setTouchScaleChangeEnabled(false)
shuxing:setFlippedX(false)
shuxing:setFlippedY(false)
shuxing:setTouchEnabled(false)
shuxing:setLayoutComponentEnabled(true)
shuxing:setName("shuxing")
shuxing:setLocalZOrder(0)
shuxing:setTag(383)
shuxing:setCascadeColorEnabled(true)
shuxing:setCascadeOpacityEnabled(true)
shuxing:setVisible(true)
shuxing:setAnchorPoint(0, 0.5)
shuxing:setPosition(6.2549, 19.0793)
shuxing:setScaleX(1)
shuxing:setScaleY(1)
shuxing:setRotation(0)
shuxing:setRotationSkewX(0)
shuxing:setRotationSkewY(0)
shuxing:setOpacity(255)
shuxing:setColor(cc.c3b(237, 196, 122))
layout = ccui.LayoutComponent:bindLayoutComponent(shuxing)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(183, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(6.2549)
layout:setRightMargin(-189.2549)
layout:setTopMargin(-31.5793)
layout:setBottomMargin(6.5793)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(shuxing)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

