--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
Layer:setLocalZOrder(0)

--Create container
local container=cc.Node:create()
container:setName("container")
container:setLocalZOrder(0)
container:setTag(3)
container:setCascadeColorEnabled(true)
container:setCascadeOpacityEnabled(true)
container:setVisible(true)
container:setAnchorPoint(0, 0)
container:setPosition(540, 360)
container:setScaleX(1)
container:setScaleY(1)
container:setRotation(0)
container:setRotationSkewX(0)
container:setRotationSkewY(0)
container:setOpacity(255)
container:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(container)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(540)
layout:setRightMargin(540)
layout:setTopMargin(360)
layout:setBottomMargin(360)
Layer:addChild(container)

--Create Sprite_2
cc.SpriteFrameCache:getInstance():addSpriteFrames("single_recharge/res/single_recharge.plist")
local Sprite_2 = cc.Sprite:createWithSpriteFrameName("single_recharge/res/1.png")
Sprite_2:setName("Sprite_2")
Sprite_2:setLocalZOrder(0)
Sprite_2:setTag(5)
Sprite_2:setCascadeColorEnabled(true)
Sprite_2:setCascadeOpacityEnabled(true)
Sprite_2:setVisible(true)
Sprite_2:setAnchorPoint(0.5, 0.5)
Sprite_2:setPosition(-502.5, 0)
Sprite_2:setScaleX(1)
Sprite_2:setScaleY(1)
Sprite_2:setRotation(0)
Sprite_2:setRotationSkewX(0)
Sprite_2:setRotationSkewY(0)
Sprite_2:setOpacity(255)
Sprite_2:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_2)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(136, 581))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-570.5)
layout:setRightMargin(434.5)
layout:setTopMargin(-290.5)
layout:setBottomMargin(-290.5)
Sprite_2:setFlippedX(false)
Sprite_2:setFlippedY(false)
container:addChild(Sprite_2)

--Create bg_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("single_recharge/res/single_recharge.plist")
local bg_1 = cc.Sprite:createWithSpriteFrameName("single_recharge/res/bg.jpg")
bg_1:setName("bg_1")
bg_1:setLocalZOrder(0)
bg_1:setTag(4)
bg_1:setCascadeColorEnabled(true)
bg_1:setCascadeOpacityEnabled(true)
bg_1:setVisible(true)
bg_1:setAnchorPoint(0.5, 0.5)
bg_1:setPosition(0, 0)
bg_1:setScaleX(1)
bg_1:setScaleY(1)
bg_1:setRotation(0)
bg_1:setRotationSkewX(0)
bg_1:setRotationSkewY(0)
bg_1:setOpacity(255)
bg_1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bg_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(870, 581))

layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(-435)
layout:setRightMargin(-435)
layout:setTopMargin(-290.5)
layout:setBottomMargin(-290.5)
bg_1:setFlippedX(false)
bg_1:setFlippedY(false)
container:addChild(bg_1)

--Create watch_btn
local watch_btn = ccui.ImageView:create()
watch_btn:ignoreContentAdaptWithSize(false)
watch_btn:loadTexture("Resources/common/bg/c_12.png",0)

watch_btn:setFlippedX(false)
watch_btn:setFlippedY(false)

watch_btn:setScale9Enabled(false)
watch_btn:setCapInsets(cc.rect(0,0,2,2))
watch_btn:setTouchEnabled(false)
watch_btn:setLayoutComponentEnabled(true)
watch_btn:setName("watch_btn")
watch_btn:setLocalZOrder(0)
watch_btn:setTag(6)
watch_btn:setCascadeColorEnabled(true)
watch_btn:setCascadeOpacityEnabled(true)
watch_btn:setVisible(true)
watch_btn:setAnchorPoint(0.5, 0.5)
watch_btn:setPosition(-158.7351, -3.3593)
watch_btn:setScaleX(1)
watch_btn:setScaleY(1)
watch_btn:setRotation(0)
watch_btn:setRotationSkewX(0)
watch_btn:setRotationSkewY(0)
watch_btn:setOpacity(255)
watch_btn:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(watch_btn)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(550, 580))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-433.7351)
layout:setRightMargin(-116.2649)
layout:setTopMargin(-286.6407)
layout:setBottomMargin(-293.3593)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
container:addChild(watch_btn)

--Create close_btn
local close_btn = ccui.ImageView:create()
close_btn:ignoreContentAdaptWithSize(false)
close_btn:loadTexture("Resources/common/bg/c_12.png",0)

close_btn:setFlippedX(false)
close_btn:setFlippedY(false)

close_btn:setScale9Enabled(false)
close_btn:setCapInsets(cc.rect(0,0,2,2))
close_btn:setTouchEnabled(false)
close_btn:setLayoutComponentEnabled(true)
close_btn:setName("close_btn")
close_btn:setLocalZOrder(0)
close_btn:setTag(8)
close_btn:setCascadeColorEnabled(true)
close_btn:setCascadeOpacityEnabled(true)
close_btn:setVisible(true)
close_btn:setAnchorPoint(0.5, 0.5)
close_btn:setPosition(392.4435, 251.5763)
close_btn:setScaleX(1)
close_btn:setScaleY(1)
close_btn:setRotation(0)
close_btn:setRotationSkewX(0)
close_btn:setRotationSkewY(0)
close_btn:setOpacity(255)
close_btn:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(close_btn)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(120, 120))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(332.4435)
layout:setRightMargin(-452.4435)
layout:setTopMargin(-311.5763)
layout:setBottomMargin(191.5763)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
container:addChild(close_btn)

--Create get_btn
local get_btn = ccui.ImageView:create()
get_btn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("single_recharge/res/single_recharge.plist")
get_btn:loadTexture("single_recharge/res/2.png",1)

get_btn:setFlippedX(false)
get_btn:setFlippedY(false)

get_btn:setScale9Enabled(false)
get_btn:setCapInsets(cc.rect(0,0,270,107))
get_btn:setTouchEnabled(false)
get_btn:setLayoutComponentEnabled(true)
get_btn:setName("get_btn")
get_btn:setLocalZOrder(0)
get_btn:setTag(7)
get_btn:setCascadeColorEnabled(true)
get_btn:setCascadeOpacityEnabled(true)
get_btn:setVisible(true)
get_btn:setAnchorPoint(0.5, 0.5)
get_btn:setPosition(255.832, -214.3315)
get_btn:setScaleX(1)
get_btn:setScaleY(1)
get_btn:setRotation(0)
get_btn:setRotationSkewX(0)
get_btn:setRotationSkewY(0)
get_btn:setOpacity(255)
get_btn:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(get_btn)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.25)
layout:setPercentHeight(0.1486)

layout:setSize(cc.size(270, 107))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(120.832)
layout:setRightMargin(-390.832)
layout:setTopMargin(160.8315)
layout:setBottomMargin(-267.8315)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
container:addChild(get_btn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

