-- 用户数据缓存

runtimeCache = {
    -- 伙伴页面缓存数据
    huobanTableOffsetY = nil,          -- tableView的Y的偏移量
    sailTableOffsetY = nil,
    responseData = nil,
    allEquipsTableOffsetY = nil,
    decorationTableOffsetY = nil,
    clothingTableOffsetY = nil,
    weaponsTableOffsetY = nil,
    runesTableOffsetY = nil,
    teamPage = nil,
    isSevenForm = false,
    sevenFormPosition = nil,
    skillViewOffSetY = nil,
    newWorldState = 0,
    newWorldGrade = 1, --选择倍数
    newWorldOutpostNum = 1, -- 挑战的关卡
    newWorldPlayerBattleInfo = nil,
    skillUpdateBtnStages = {},
    skillUpdateMaterialArray = {},
    chapterFight = {}, -- 残章抢夺数据
    publicChatData = {},
    publicChatTime = 0,
    leagueChatData = {},
    leagueChatTime = 0,
    campChatData = {},
    campChatTime = 0,
    mailData = {},
    bVideo = false,
    bPlayStageTalk = false, -- 是否播放剧情
    bFirstEnterMain = true, -- 是否首次登陆游戏成功
    stageId = nil, -- 挑战的关卡
    guideStep = 1,
    bGuide = true,
    levelGuideNext = nil,
    singSelectHeroId = nil,
    firstIn = nil,
    breakSkillType = 0,
    opAniStep = 0, -- 开场动画步骤
    equipFromeTeam = 0,
    buySuccessItemId = nil,
    bLevelGuide = false,
    gotoDailyPage = -1,
    newWorldSkip = 2, -- 血战跳过
    marinePageNum = 0,
    dailyPageNum = nil,
    -- isShadow = 0,   -- 阵容还是影子
    teamState = 0, -- 0 阵容 1 影子 2 霸气
    equipPageNum = 0, -- 装备
    unionBattleBack = false,
    unionBattleInFight = false, -- 盟战是否进入战斗
    isSecretShopRefresh = false,      -- 神秘商店是否刷新
    veiledState = 0,
    veiledSeaMapLayer = {},   --迷雾之海地图
    SSAState = nil,
    UnionRacingBattle_BeginTime = 0, --联盟竞速战,玩家开始战斗的时间
    hakiGetByOpenBattle = 0,
    payCashAmount = 0.00,
}


--重置缓存数据
function runtimeCache:resetAllData()
    runtimeCache.huobanTableOffsetY = nil
    runtimeCache.sailTableOffsetY = nil
    runtimeCache.responseData = nil
    runtimeCache.allEquipsTableOffsetY = nil
    runtimeCache.decorationTableOffsetY = nil
    runtimeCache.clothingTableOffsetY = nil
    runtimeCache.weaponsTableOffsetY = nil
    runtimeCache.runesTableOffsetY = nil
    runtimeCache.teamPage = nil
    runtimeCache.isSevenForm = false
    runtimeCache.sevenFormPosition = nil
    runtimeCache.skillViewOffSetY = nil
    runtimeCache.newWorldState = 0
    runtimeCache.newWorldGrade = 1
    runtimeCache.newWorldOutpostNum = 1
    runtimeCache.newWorldPlayerBattleInfo = nil
    runtimeCache.skillUpdateBtnStages = {}
    runtimeCache.skillUpdateMaterialArray = {}
    runtimeCache.chapterFight = {}
    runtimeCache.publicChatData = {}
    runtimeCache.publicChatTime = 0
    runtimeCache.leagueChatData = {}
    runtimeCache.leagueChatTime = 0
    runtimeCache.campChatData = {}
    runtimeCache.campChatTime = 0
    runtimeCache.mailData = {}
    runtimeCache.bVideo = false
    runtimeCache.bPlayStageTalk = false
    runtimeCache.bFirstEnterMain = true
    runtimeCache.guideStep = 1
    runtimeCache.bGuide = false
    runtimeCache.levelGuideNext = nil
    runtimeCache.stageId = nil 
    runtimeCache.singSelectHeroId = nil
    runtimeCache.firstIn = nil
    runtimeCache.breakSkillType = 0
    runtimeCache.opAniStep = 0
    runtimeCache.equipFromeTeam = 0
    runtimeCache.buySuccessItemId = 0
    runtimeCache.bLevelGuide = false
    runtimeCache.gotoDailyPage = -1
    runtimeCache.newWorldSkip = 2
    runtimeCache.dailyPageNum = nil
    -- runtimeCache.isShadow = 0
    runtimeCache.teamState = 0 -- 0 阵容 1 影子 2 霸气
    runtimeCache.equipPageNum = 0
    runtimeCache.unionBattleBack = false
    runtimeCache.unionBattleInFight = false
    runtimeCache.isSecretShopRefresh = false
    runtimeCache.veiledSeaState = 0
    runtimeCache.veiledSeaMapLayer = {}
    runtimeCache.recruitOption = nil
    runtimeCache.SSAState = 0 --新增跨服决斗
    -- runtimeCache.veiledSeaMapLayer = {}
    runtimeCache.unionRacingBattleBack = false
    runtimeCache.unionRacingBattleBossBack = false
    runtimeCache.UnionRacingBattle_BeginTime = nil --联盟竞速战,玩家开始战斗的时间
    runtimeCache.hakiGetByOpenBattle = 0
    runtimeCache.payCashAmount = 0.00
end

