--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("taste_war/res/di.png",0)

bg:setFlippedX(false)
bg:setFlippedY(false)

bg:setScale9Enabled(true)
bg:setCapInsets(cc.rect(124,37,128,40))
bg:setTouchEnabled(false)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setLocalZOrder(0)
bg:setTag(57)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setVisible(true)
bg:setAnchorPoint(0.5, 0.5)
bg:setPosition(294, 57)
bg:setScaleX(1)
bg:setScaleY(1)
bg:setRotation(0)
bg:setRotationSkewX(0)
bg:setRotationSkewY(0)
bg:setOpacity(255)
bg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(585, 114))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(1.5)
layout:setRightMargin(-586.5)
layout:setTopMargin(-114)
layout:setBottomMargin(0)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(bg)

--Create awardbg
local awardbg = ccui.ImageView:create()
awardbg:ignoreContentAdaptWithSize(false)
awardbg:loadTexture("Resources/common/bg/c_12.png",0)

awardbg:setFlippedX(false)
awardbg:setFlippedY(false)

awardbg:setScale9Enabled(false)
awardbg:setCapInsets(cc.rect(0,0,2,2))
awardbg:setTouchEnabled(false)
awardbg:setLayoutComponentEnabled(true)
awardbg:setName("awardbg")
awardbg:setLocalZOrder(0)
awardbg:setTag(58)
awardbg:setCascadeColorEnabled(true)
awardbg:setCascadeOpacityEnabled(true)
awardbg:setVisible(true)
awardbg:setAnchorPoint(0.5, 0.5)
awardbg:setPosition(67, 58)
awardbg:setScaleX(1)
awardbg:setScaleY(1)
awardbg:setRotation(0)
awardbg:setRotationSkewX(0)
awardbg:setRotationSkewY(0)
awardbg:setOpacity(255)
awardbg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(awardbg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.1145)
layout:setPositionPercentY(0.5088)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.2222)
layout:setPercentHeight(0.9649)

layout:setSize(cc.size(130, 110))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(2)
layout:setRightMargin(453)
layout:setTopMargin(1)
layout:setBottomMargin(3)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(awardbg)

--Create name
local name = ccui.Text:create()
name:ignoreContentAdaptWithSize(true)
name:setTextAreaSize(cc.size(0, 0))
name:setFontName("Resources/font/ttf/black_body.TTF")
name:setFontSize(22)
name:setString([[道具名称]])
name:setTextHorizontalAlignment(0)
name:setTextVerticalAlignment(0)
name:setTouchScaleChangeEnabled(false)
name:setFlippedX(false)
name:setFlippedY(false)
name:enableShadow(cc.c4b(26, 26, 26, 255), cc.size(2, -2), 0)
name:enableOutline(cc.c4b(26, 26, 26, 255), 0)
name:setTouchEnabled(false)
name:setLayoutComponentEnabled(true)
name:setName("name")
name:setLocalZOrder(0)
name:setTag(59)
name:setCascadeColorEnabled(true)
name:setCascadeOpacityEnabled(true)
name:setVisible(true)
name:setAnchorPoint(0, 0.5)
name:setPosition(153.5, 92)
name:setScaleX(1)
name:setScaleY(1)
name:setRotation(0)
name:setRotationSkewX(0)
name:setRotationSkewY(0)
name:setOpacity(255)
name:setColor(cc.c3b(235, 179, 78))
layout = ccui.LayoutComponent:bindLayoutComponent(name)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.2624)
layout:setPositionPercentY(0.807)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(88, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(153.5)
layout:setRightMargin(343.5)
layout:setTopMargin(9.5)
layout:setBottomMargin(79.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(name)

--Create enchange
local enchange = ccui.Text:create()
enchange:ignoreContentAdaptWithSize(true)
enchange:setTextAreaSize(cc.size(0, 0))
enchange:setFontName("Resources/font/ttf/black_body.TTF")
enchange:setFontSize(22)
enchange:setString([[兑换所需：77]])
enchange:setTextHorizontalAlignment(0)
enchange:setTextVerticalAlignment(0)
enchange:setTouchScaleChangeEnabled(false)
enchange:setFlippedX(false)
enchange:setFlippedY(false)
enchange:enableShadow(cc.c4b(26, 26, 26, 255), cc.size(2, -2), 0)
enchange:enableOutline(cc.c4b(26, 26, 26, 255), 0)
enchange:setTouchEnabled(false)
enchange:setLayoutComponentEnabled(true)
enchange:setName("enchange")
enchange:setLocalZOrder(0)
enchange:setTag(60)
enchange:setCascadeColorEnabled(true)
enchange:setCascadeOpacityEnabled(true)
enchange:setVisible(true)
enchange:setAnchorPoint(0, 0.5)
enchange:setPosition(153.5, 38)
enchange:setScaleX(1)
enchange:setScaleY(1)
enchange:setRotation(0)
enchange:setRotationSkewX(0)
enchange:setRotationSkewY(0)
enchange:setOpacity(255)
enchange:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(enchange)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.2624)
layout:setPositionPercentY(0.3333)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(138, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(153.5)
layout:setRightMargin(343.5)
layout:setTopMargin(63.5)
layout:setBottomMargin(25.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(enchange)

--Create buyBt
local buyBt = ccui.Button:create()
buyBt:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
buyBt:loadTextureNormal("Resources/common/button/btn_3.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
buyBt:loadTexturePressed("Resources/common/button/anniuhong02.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
buyBt:loadTextureDisabled("Resources/common/button/anniuhui.png",1)
buyBt:setTitleFontSize(14)
buyBt:setTitleText("")
buyBt:setTitleColor(cc.c3b(65, 65, 70))
buyBt:setFlippedX(false)
buyBt:setFlippedY(false)
buyBt:setScale9Enabled(true)
buyBt:setCapInsets(cc.rect(15,11,122,44))
buyBt:setBright(true)
buyBt:setTouchEnabled(true)
buyBt:setLayoutComponentEnabled(true)
buyBt:setName("buyBt")
buyBt:setLocalZOrder(0)
buyBt:setTag(61)
buyBt:setCascadeColorEnabled(true)
buyBt:setCascadeOpacityEnabled(true)
buyBt:setVisible(true)
buyBt:setAnchorPoint(0.5, 0.5)
buyBt:setPosition(506, 65)
buyBt:setScaleX(1)
buyBt:setScaleY(1)
buyBt:setRotation(0)
buyBt:setRotationSkewX(0)
buyBt:setRotationSkewY(0)
buyBt:setOpacity(255)
buyBt:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(buyBt)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.865)
layout:setPositionPercentY(0.5702)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.2051)
layout:setPercentHeight(0.5789)

layout:setSize(cc.size(120, 66))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(446)
layout:setRightMargin(19)
layout:setTopMargin(16)
layout:setBottomMargin(32)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(buyBt)

--Create Image_3
local Image_3 = ccui.ImageView:create()
Image_3:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("taste_war/res/tastewar.plist")
Image_3:loadTexture("taste_war/res/duihuan.png",1)

Image_3:setFlippedX(false)
Image_3:setFlippedY(false)

Image_3:setScale9Enabled(false)
Image_3:setCapInsets(cc.rect(0,0,62,22))
Image_3:setTouchEnabled(false)
Image_3:setLayoutComponentEnabled(true)
Image_3:setName("Image_3")
Image_3:setLocalZOrder(0)
Image_3:setTag(62)
Image_3:setCascadeColorEnabled(true)
Image_3:setCascadeOpacityEnabled(true)
Image_3:setVisible(true)
Image_3:setAnchorPoint(0.5, 0.5)
Image_3:setPosition(61, 34)
Image_3:setScaleX(1)
Image_3:setScaleY(1)
Image_3:setRotation(0)
Image_3:setRotationSkewX(0)
Image_3:setRotationSkewY(0)
Image_3:setOpacity(255)
Image_3:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Image_3)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5083)
layout:setPositionPercentY(0.5152)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.5167)
layout:setPercentHeight(0.3333)

layout:setSize(cc.size(62, 22))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(30)
layout:setRightMargin(28)
layout:setTopMargin(21)
layout:setBottomMargin(23)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
buyBt:addChild(Image_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

