var NOTI = {
	PLATFORM_LOGIN_SUCC:"PLATFORM_LOGIN_SUCC",
	LOGIN_SUCC:"LOGIN_SUCC",
	STARTGAME_NOTI:"STARTGAME_NOTI",
	GET_SETTING:"GET_SETTING",
	SHOW_MAIN:"SHOW_MAIN",
	LOGOUTACTION:"LOGOUTACTION",
	SHOW_UPADTE:"SHOW_UPDATE",
	SHOW_CREATE_NAME:"SHOW_CREATE_NAME",
	SHOW_SELECT_HERO:"SHOW_SELECT_HERO",
	
	// 数据
	NOTI_DATA_UPDATE:"NOTI_DATA_UPDATE",
	BERRY_REFRESH:"BERRY_REFRESH",
	GOLD_REFRESH:"GOLD_REFRESH",
	ST_REFRESH:"ST_REFRESH",
	EN_REFRESH:"EN_REFRESH",
	
	// 跳转
	GOTO_HOME:"GOTO_HOME",
	GOTO_TEAM:"GOTO_TEAM",
	GOTO_HEROES:"GOTO_HEROES",
	GOTO_FAREWELL:"GOTO_FAREWELL",
	GOTO_BREAK:"GOTO_BREAK",
	GOTO_FAREWELLSELHERO:"GOTO_FAREWELLSELHERO",
	GOTO_CULTURE:"GOTO_CULTURE",
	GOTO_ONFORM:"GOTO_ONFORM",
	GOTO_SKILLS:"GOTO_SKILLS",
	GOTO_SKILL_BREAK:"GOTO_SKILL_BREAK",
	GOTO_SKILL_BREAK_SELECT:"GOTO_SKILL_BREAK_SELECT",
	GOTO_SKILL_BREAK_RESULT:"GOTO_SKILL_BREAK_RESULT",
	GOTO_SKILL_CHANGE:"GOTO_SKILL_CHANGE",
	GOTO_PACKAGE:"GOTO_PACKAGE",
	GOTO_EQUIPS:"GOTO_EQUIPS",
	GOTO_EQUIPSELL:"GOTO_EQUIPSELL",
	GOTO_EQUIPUPDATE:"GOTO_EQUIPUPDATE",

	GOTO_DAILY:"GOTO_DAILY",
	GOTO_GETSOMEAWARD:"GOTO_GETSOMEAWAR",
	GOTO_ATLAS:"GOTO_ATLAS",
	GOTO_NEWS:"GOTO_NEWS",
	GOTO_FRIEND:"GOTO_FRIEND",
	GOTO_EQUIP_CHANGE:"GOTO_EQUIP_CHANGE",
	GOTO_SHOPBUYSOMEPOPUP:"GOTO_SHOPBUYSOMEPOPUP",
	GOTO_CHAT:"GOTO_CHAT",
	GOTO_SYSTEM:"GOTO_SYSTEM",
	GOTO_UNION:"GOTO_UNION",
	GOTO_STAGE:"GOTO_STAGE",
	GOTO_FIGHT:"GOTO_FIGHT",
	
	//服务器列表
	GET_SERVERLIST:"GET_SERVERLIST",
	
	// 阵容
	TEAM_CHANGE_TYPE:"TEAM_CHANGE_TYPE",
	FORM_CHANGE_SUCC:"FORM_CHANGE_SUCC",
	
	// 啦啦队
	LALA_REFRESH:"LALA_REFRESH",
	TRINGSHADOW_CD_TIME:"TRINGSHADOW_CD_TIME",
	SHADOW_WAVE_REFRESH:"SHADOW_WAVE_REFRESH",
	SHADOW_CHANGE_UI:"SHADOW_CHANGE_UI",
	
	// 背包
	REFRESH_PACKAGE:"REFRESH_PACKAGE",

	// 影子
	SHADOW_CHANGE_EXP:"SHADOW_CHANGE_EXP",
	GOTO_SHADOW:"GOTO_SHADOW",
	GOTO_SHADOW_UPDATE:"GOTO_SHADOW_UPDATE",
	REFRESH_SHADOW_VIEW:"REFRESH_SHADOW_VIEW",
	GOTO_SHADOW_CHANGE:"GOTO_SHADOW_CHANGE",
	
	// 大冒险新世界
	GOTO_ADVENTURE:"GOTO_ADVENTURE",
	BLOOD_REFRESH_STATE:"BLOOD_REFRESH_STATE",
	MOVETO_PAGE:"MOVETO_PAGE",
	

	//罗格镇
	GOTO_LOGUETOWN:"GOTO_LOGUETOWN",

	// 活动数据发生改变
	ACTIVITY_DATA_CHANGE:"ACTIVITY_DATA_CHANGE",
	
	//boss时间刷新
	BOSS_TIME_REFRESH:"BOSS_TIME_REFRESH",
	BOSS_RESURRECT:"BOSS_RESURRECT",
	BOSS_AUTO_FIGHT:"BOSS_AUTO_FIGHT",
	BOSS_CLOSE_CHALLENGE:"BOSS_CLOSE_CHALLENGE",
	BOSS_CHALLENGE:"BOSS_CHALLENGE",
	
	//残页抢夺
	GOTO_CHAPTER_ROB:"GOTO_CHAPTER_ROB",
	
	//决斗
	GOTO_ARENA:"GOTO_ARENA",
	REFRESH_ARENA_INFO:"REFRESH_ARENA_INFO",
	REFRESH_ARENA_CALLBACK:"REFRESH_ARENA_CALLBACK",

	// 公会
	UNION_MAIN_REFRESH:"UNION_MAIN_REFRESH",
	UNION_CHANGESTATE:"UNION_CHANGESTATE",
	UNION_ML_VISIBLE:"UNION_ML_VISIBLE",
	UNION_MANAGE_REFRESH:"UNION_MANAGE_REFRESH",
	UNION_MEMBER_REFRESH:"UNION_MEMBER_REFRESH",
	UNION_CANDY_REFRESH:"UNION_CANDY_REFRESH",
	UNION_SHOP_REFRESH:"UNION_SHOP_REFRESH",
	
	// 任务系统
	GOTO_QUEST:"GOTO_QUEST",
	REFRESH_QEUEST:"REFRESH_QEUEST",
	
	//更新下载
	SHOW_UPDATE_LAYER:"SHOW_UPDATE_LAYER",
	DO_LOADING:"DO_LOADING",
	
	// 活动时间更新
	ACIVITY_TIME_UPDATE : "ACIVITY_TIME_UPDATE",
	ACTIVITY_DAILY_LIST_CHANGE : "ACTIVITY_DAILY_LIST_CHANGE",

	// 战斗
	FIGHT_VEDIO:"FIGHT_VEDIO",
	STAGE_REFRESH:"STAGE_REFRESH",
	
	// 工坊视图切换
	DAILY_CREAFTS_MAN_CHANGE_VIEW:"DAILY_CREAFTS_MAN_CHANGE_VIEW",

	//设置
	GOTO_HELP:"GOTO_HELP",
	GOTO_CUSSERVICE:"GOTO_CUSSERVICE",

	// 好友
	FRFRESH_FRIEND_LAYER :"FRFRESH_FRIEND_LAYER",
	GOTO_ADD_FRIEND : "GOTO_ADD_FRIEND",
	REFRESH_ADDFRIEND_LAYER : "REFRESH_ADDFRIEND_LAYER",
	
	//招募
	RESURIT_HERO : "RESURIT_HERO",
	
	//体力，精力
	STRENGTH : "STRENGTH",
	
	//聊天数据
	REFRESH_ALLCHATDATA : "REFRESH_ALLCHATDATA",
	
	//新闻页面
	REFRESH_MAIL_LAYER : "REFRESH_MAIL_LAYER",
	
	//新手引导
	GOTO_GUIDE : "GOTO_GUIDE",
	
	//前往充值页面
	GOTO_CHONGZHI : "GOTO_CHONGZHI",
}