--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create scrollView
local scrollView = ccui.ScrollView:create()

scrollView:setBounceEnabled(false)
scrollView:setDirection(1)
scrollView:setInnerContainerSize(cc.size(750,480))

scrollView:ignoreContentAdaptWithSize(false)

scrollView:setClippingEnabled(true)
scrollView:setBackGroundImageCapInsets(cc.rect(0,0,1,1))
scrollView:setBackGroundColor(cc.c3b(255, 150, 100))
scrollView:setBackGroundColor(cc.c3b(255, 150, 100),cc.c3b(255, 255, 255))
scrollView:setBackGroundColorVector(cc.p(0,1))
scrollView:setBackGroundColorType(0)
scrollView:setBackGroundColorOpacity(102)
scrollView:setBackGroundImageScale9Enabled(false)

scrollView:setTouchEnabled(true)
scrollView:setLayoutComponentEnabled(true)
scrollView:setName("scrollView")
scrollView:setLocalZOrder(0)
scrollView:setTag(27)
scrollView:setCascadeColorEnabled(true)
scrollView:setCascadeOpacityEnabled(true)
scrollView:setVisible(true)
scrollView:setAnchorPoint(0, 1)
scrollView:setPosition(11, 489)
scrollView:setScaleX(1)
scrollView:setScaleY(1)
scrollView:setRotation(0)
scrollView:setRotationSkewX(0)
scrollView:setRotationSkewY(0)
scrollView:setOpacity(255)
scrollView:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(scrollView)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(750, 415))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(11)
layout:setRightMargin(-761)
layout:setTopMargin(-489)
layout:setBottomMargin(74)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(scrollView)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

