--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
Layer:setLocalZOrder(0)

--Create Pages
local Pages = ccui.Text:create()
Pages:ignoreContentAdaptWithSize(true)
Pages:setTextAreaSize(cc.size(0, 0))
Pages:setFontName("Resources/font/ttf/black_body_2.TTF")
Pages:setFontSize(22)
Pages:setString([[1/71]])
Pages:setTextHorizontalAlignment(0)
Pages:setTextVerticalAlignment(0)
Pages:setTouchScaleChangeEnabled(false)
Pages:setFlippedX(false)
Pages:setFlippedY(false)
Pages:setTouchEnabled(false)
Pages:setLayoutComponentEnabled(true)
Pages:setName("Pages")
Pages:setLocalZOrder(0)
Pages:setTag(149)
Pages:setCascadeColorEnabled(true)
Pages:setCascadeOpacityEnabled(true)
Pages:setVisible(true)
Pages:setAnchorPoint(0.5, 0.5)
Pages:setPosition(540, 127.0002)
Pages:setScaleX(1)
Pages:setScaleY(1)
Pages:setRotation(0)
Pages:setRotationSkewX(0)
Pages:setRotationSkewY(0)
Pages:setOpacity(255)
Pages:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Pages)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.1764)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(45, 25))

layout:setHorizontalEdge(3)
layout:setVerticalEdge(0)
layout:setLeftMargin(517.5)
layout:setRightMargin(517.5)
layout:setTopMargin(580.4998)
layout:setBottomMargin(114.5002)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Layer:addChild(Pages)

--Create BtnRight
local BtnRight = ccui.ImageView:create()
BtnRight:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("carray/res/res.plist")
BtnRight:loadTexture("carray/res/jiantou1.png",1)

BtnRight:setFlippedX(true)
BtnRight:setFlippedY(false)

BtnRight:setScale9Enabled(false)
BtnRight:setCapInsets(cc.rect(0,0,34,52))
BtnRight:setTouchEnabled(false)
BtnRight:setLayoutComponentEnabled(true)
BtnRight:setName("BtnRight")
BtnRight:setLocalZOrder(0)
BtnRight:setTag(148)
BtnRight:setCascadeColorEnabled(true)
BtnRight:setCascadeOpacityEnabled(true)
BtnRight:setVisible(true)
BtnRight:setAnchorPoint(0.5, 0.5)
BtnRight:setPosition(72, 11.5001)
BtnRight:setScaleX(1)
BtnRight:setScaleY(1)
BtnRight:setRotation(0)
BtnRight:setRotationSkewX(0)
BtnRight:setRotationSkewY(0)
BtnRight:setOpacity(255)
BtnRight:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(BtnRight)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(1.6)
layout:setPositionPercentY(0.46)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.0315)
layout:setPercentHeight(0.0722)

layout:setSize(cc.size(34, 52))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(55)
layout:setRightMargin(-44)
layout:setTopMargin(-12.5001)
layout:setBottomMargin(-14.4999)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Pages:addChild(BtnRight)

--Create BtnLeft
local BtnLeft = ccui.ImageView:create()
BtnLeft:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("carray/res/res.plist")
BtnLeft:loadTexture("carray/res/jiantou1.png",1)

BtnLeft:setFlippedX(false)
BtnLeft:setFlippedY(false)

BtnLeft:setScale9Enabled(false)
BtnLeft:setCapInsets(cc.rect(0,0,34,52))
BtnLeft:setTouchEnabled(false)
BtnLeft:setLayoutComponentEnabled(true)
BtnLeft:setName("BtnLeft")
BtnLeft:setLocalZOrder(0)
BtnLeft:setTag(147)
BtnLeft:setCascadeColorEnabled(true)
BtnLeft:setCascadeOpacityEnabled(true)
BtnLeft:setVisible(true)
BtnLeft:setAnchorPoint(0.5, 0.5)
BtnLeft:setPosition(-31, 11.5001)
BtnLeft:setScaleX(1)
BtnLeft:setScaleY(1)
BtnLeft:setRotation(0)
BtnLeft:setRotationSkewX(0)
BtnLeft:setRotationSkewY(0)
BtnLeft:setOpacity(255)
BtnLeft:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(BtnLeft)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(-0.6889)
layout:setPositionPercentY(0.46)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.0315)
layout:setPercentHeight(0.0722)

layout:setSize(cc.size(34, 52))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-48)
layout:setRightMargin(59)
layout:setTopMargin(-12.5001)
layout:setBottomMargin(-14.4999)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Pages:addChild(BtnLeft)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

