--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create Sprite_1
local Sprite_1 = cc.Sprite:create("group_battles/res/1.jpg")
Sprite_1:setName("Sprite_1")
Sprite_1:setLocalZOrder(0)
Sprite_1:setTag(83)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setVisible(true)
Sprite_1:setAnchorPoint(0.5, 0.5)
Sprite_1:setPosition(44, 240)
Sprite_1:setScaleX(1)
Sprite_1:setScaleY(1)
Sprite_1:setRotation(0)
Sprite_1:setRotationSkewX(0)
Sprite_1:setRotationSkewY(0)
Sprite_1:setOpacity(255)
Sprite_1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(239, 169))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-75.5)
layout:setRightMargin(-163.5)
layout:setTopMargin(-324.5)
layout:setBottomMargin(155.5)
Sprite_1:setFlippedX(false)
Sprite_1:setFlippedY(false)
Node:addChild(Sprite_1)

--Create Sprite_8
local Sprite_8 = cc.Sprite:create("group_battles/res/2.jpg")
Sprite_8:setName("Sprite_8")
Sprite_8:setLocalZOrder(0)
Sprite_8:setTag(90)
Sprite_8:setCascadeColorEnabled(true)
Sprite_8:setCascadeOpacityEnabled(true)
Sprite_8:setVisible(true)
Sprite_8:setAnchorPoint(0.5, 0.5)
Sprite_8:setPosition(279, 19)
Sprite_8:setScaleX(1)
Sprite_8:setScaleY(1)
Sprite_8:setRotation(0)
Sprite_8:setRotationSkewX(0)
Sprite_8:setRotationSkewY(0)
Sprite_8:setOpacity(255)
Sprite_8:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_8)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(239, 169))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(159.5)
layout:setRightMargin(-398.5)
layout:setTopMargin(-103.5)
layout:setBottomMargin(-65.5)
Sprite_8:setFlippedX(false)
Sprite_8:setFlippedY(false)
Node:addChild(Sprite_8)

--Create Sprite_10
local Sprite_10 = cc.Sprite:create("group_battles/res/3.jpg")
Sprite_10:setName("Sprite_10")
Sprite_10:setLocalZOrder(0)
Sprite_10:setTag(92)
Sprite_10:setCascadeColorEnabled(true)
Sprite_10:setCascadeOpacityEnabled(true)
Sprite_10:setVisible(true)
Sprite_10:setAnchorPoint(0.5, 0.5)
Sprite_10:setPosition(67, -73)
Sprite_10:setScaleX(1)
Sprite_10:setScaleY(1)
Sprite_10:setRotation(0)
Sprite_10:setRotationSkewX(0)
Sprite_10:setRotationSkewY(0)
Sprite_10:setOpacity(255)
Sprite_10:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_10)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(239, 169))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-52.5)
layout:setRightMargin(-186.5)
layout:setTopMargin(-11.5)
layout:setBottomMargin(-157.5)
Sprite_10:setFlippedX(false)
Sprite_10:setFlippedY(false)
Node:addChild(Sprite_10)

--Create Sprite_12
local Sprite_12 = cc.Sprite:create("group_battles/res/4.jpg")
Sprite_12:setName("Sprite_12")
Sprite_12:setLocalZOrder(0)
Sprite_12:setTag(94)
Sprite_12:setCascadeColorEnabled(true)
Sprite_12:setCascadeOpacityEnabled(true)
Sprite_12:setVisible(true)
Sprite_12:setAnchorPoint(0.5, 0.5)
Sprite_12:setPosition(232, 178)
Sprite_12:setScaleX(1)
Sprite_12:setScaleY(1)
Sprite_12:setRotation(0)
Sprite_12:setRotationSkewX(0)
Sprite_12:setRotationSkewY(0)
Sprite_12:setOpacity(255)
Sprite_12:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_12)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(239, 169))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(112.5)
layout:setRightMargin(-351.5)
layout:setTopMargin(-262.5)
layout:setBottomMargin(93.5)
Sprite_12:setFlippedX(false)
Sprite_12:setFlippedY(false)
Node:addChild(Sprite_12)

--Create Sprite_14
local Sprite_14 = cc.Sprite:create("group_battles/res/5.jpg")
Sprite_14:setName("Sprite_14")
Sprite_14:setLocalZOrder(0)
Sprite_14:setTag(96)
Sprite_14:setCascadeColorEnabled(true)
Sprite_14:setCascadeOpacityEnabled(true)
Sprite_14:setVisible(true)
Sprite_14:setAnchorPoint(0.5, 0.5)
Sprite_14:setPosition(296, -82)
Sprite_14:setScaleX(1)
Sprite_14:setScaleY(1)
Sprite_14:setRotation(0)
Sprite_14:setRotationSkewX(0)
Sprite_14:setRotationSkewY(0)
Sprite_14:setOpacity(255)
Sprite_14:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_14)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(239, 169))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(176.5)
layout:setRightMargin(-415.5)
layout:setTopMargin(-2.5)
layout:setBottomMargin(-166.5)
Sprite_14:setFlippedX(false)
Sprite_14:setFlippedY(false)
Node:addChild(Sprite_14)

--Create Sprite_16
local Sprite_16 = cc.Sprite:create("group_battles/res/6.jpg")
Sprite_16:setName("Sprite_16")
Sprite_16:setLocalZOrder(0)
Sprite_16:setTag(98)
Sprite_16:setCascadeColorEnabled(true)
Sprite_16:setCascadeOpacityEnabled(true)
Sprite_16:setVisible(true)
Sprite_16:setAnchorPoint(0.5, 0.5)
Sprite_16:setPosition(-186, 106)
Sprite_16:setScaleX(1)
Sprite_16:setScaleY(1)
Sprite_16:setRotation(0)
Sprite_16:setRotationSkewX(0)
Sprite_16:setRotationSkewY(0)
Sprite_16:setOpacity(255)
Sprite_16:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_16)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(239, 169))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-305.5)
layout:setRightMargin(66.5)
layout:setTopMargin(-190.5)
layout:setBottomMargin(21.5)
Sprite_16:setFlippedX(false)
Sprite_16:setFlippedY(false)
Node:addChild(Sprite_16)

--Create Sprite_3
local Sprite_3 = cc.Sprite:create("group_battles/res/7.jpg")
Sprite_3:setName("Sprite_3")
Sprite_3:setLocalZOrder(0)
Sprite_3:setTag(66)
Sprite_3:setCascadeColorEnabled(true)
Sprite_3:setCascadeOpacityEnabled(true)
Sprite_3:setVisible(true)
Sprite_3:setAnchorPoint(0.5, 0.5)
Sprite_3:setPosition(-165, -76)
Sprite_3:setScaleX(1)
Sprite_3:setScaleY(1)
Sprite_3:setRotation(0)
Sprite_3:setRotationSkewX(0)
Sprite_3:setRotationSkewY(0)
Sprite_3:setOpacity(255)
Sprite_3:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_3)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(239, 169))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-284.5)
layout:setRightMargin(45.5)
layout:setTopMargin(-8.5)
layout:setBottomMargin(-160.5)
Sprite_3:setFlippedX(false)
Sprite_3:setFlippedY(false)
Node:addChild(Sprite_3)

--Create Sprite_4
local Sprite_4 = cc.Sprite:create("group_battles/res/8.jpg")
Sprite_4:setName("Sprite_4")
Sprite_4:setLocalZOrder(0)
Sprite_4:setTag(67)
Sprite_4:setCascadeColorEnabled(true)
Sprite_4:setCascadeOpacityEnabled(true)
Sprite_4:setVisible(true)
Sprite_4:setAnchorPoint(0.5, 0.5)
Sprite_4:setPosition(193, -262)
Sprite_4:setScaleX(1)
Sprite_4:setScaleY(1)
Sprite_4:setRotation(0)
Sprite_4:setRotationSkewX(0)
Sprite_4:setRotationSkewY(0)
Sprite_4:setOpacity(255)
Sprite_4:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_4)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(239, 169))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(73.5)
layout:setRightMargin(-312.5)
layout:setTopMargin(177.5)
layout:setBottomMargin(-346.5)
Sprite_4:setFlippedX(false)
Sprite_4:setFlippedY(false)
Node:addChild(Sprite_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

