--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("accessories/res/bg2.png",0)

bg:setFlippedX(false)
bg:setFlippedY(false)

bg:setScale9Enabled(true)
bg:setCapInsets(cc.rect(84,43,87,46))
bg:setTouchEnabled(false)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setLocalZOrder(0)
bg:setTag(162)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setVisible(true)
bg:setAnchorPoint(0.5, 0.5)
bg:setPosition(102, 63)
bg:setScaleX(1)
bg:setScaleY(1)
bg:setRotation(0)
bg:setRotationSkewX(0)
bg:setRotationSkewY(0)
bg:setOpacity(255)
bg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(200, 120))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(2)
layout:setRightMargin(-202)
layout:setTopMargin(-123)
layout:setBottomMargin(3)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(bg)

--Create bt
local bt = ccui.ImageView:create()
bt:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/img/common_img.plist")
bt:loadTexture("Resources/common/img/BK_t6.png",1)

bt:setFlippedX(false)
bt:setFlippedY(false)

bt:setScale9Enabled(false)
bt:setCapInsets(cc.rect(0,0,50,50))
bt:setTouchEnabled(false)
bt:setLayoutComponentEnabled(true)
bt:setName("bt")
bt:setLocalZOrder(0)
bt:setTag(163)
bt:setCascadeColorEnabled(true)
bt:setCascadeOpacityEnabled(true)
bt:setVisible(true)
bt:setAnchorPoint(0.5, 0.5)
bt:setPosition(161, 62.5622)
bt:setScaleX(1)
bt:setScaleY(1)
bt:setRotation(0)
bt:setRotationSkewX(0)
bt:setRotationSkewY(0)
bt:setOpacity(255)
bt:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bt)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.805)
layout:setPositionPercentY(0.5214)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(50, 50))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(136)
layout:setRightMargin(14)
layout:setTopMargin(32.4378)
layout:setBottomMargin(37.5622)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(bt)

--Create btbg
local btbg = ccui.ImageView:create()
btbg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/img/common_img.plist")
btbg:loadTexture("Resources/common/img/XL_3.png",1)

btbg:setFlippedX(false)
btbg:setFlippedY(false)

btbg:setScale9Enabled(false)
btbg:setCapInsets(cc.rect(0,0,64,49))
btbg:setTouchEnabled(false)
btbg:setLayoutComponentEnabled(true)
btbg:setName("btbg")
btbg:setLocalZOrder(0)
btbg:setTag(164)
btbg:setCascadeColorEnabled(true)
btbg:setCascadeOpacityEnabled(true)
btbg:setVisible(true)
btbg:setAnchorPoint(0.4844, 0.456)
btbg:setPosition(24, 23.8451)
btbg:setScaleX(1)
btbg:setScaleY(1)
btbg:setRotation(0)
btbg:setRotationSkewX(0)
btbg:setRotationSkewY(0)
btbg:setOpacity(255)
btbg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(btbg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.48)
layout:setPositionPercentY(0.4769)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.8)
layout:setPercentHeight(0.8)

layout:setSize(cc.size(40, 40))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(4.624)
layout:setRightMargin(5.376)
layout:setTopMargin(4.3949)
layout:setBottomMargin(5.6051)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bt:addChild(btbg)

--Create partbg
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/item/common_item.plist")
local partbg = cc.Sprite:createWithSpriteFrameName("Resources/common/item/item_bg_1.png")
partbg:setName("partbg")
partbg:setLocalZOrder(0)
partbg:setTag(10)
partbg:setCascadeColorEnabled(true)
partbg:setCascadeOpacityEnabled(true)
partbg:setVisible(true)
partbg:setAnchorPoint(0.5, 0.5)
partbg:setPosition(65.9995, 58.9994)
partbg:setScaleX(0.95)
partbg:setScaleY(0.95)
partbg:setRotation(0)
partbg:setRotationSkewX(0)
partbg:setRotationSkewY(0)
partbg:setOpacity(255)
partbg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(partbg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.33)
layout:setPositionPercentY(0.4917)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(113, 113))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(9.4995)
layout:setRightMargin(77.5005)
layout:setTopMargin(4.5006)
layout:setBottomMargin(2.4994)
partbg:setFlippedX(false)
partbg:setFlippedY(false)
bg:addChild(partbg)

--Create part
local part = ccui.ImageView:create()
part:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("accessories/res/Part.plist")
part:loadTexture("accessories/res/part5.png",1)

part:setFlippedX(false)
part:setFlippedY(false)

part:setScale9Enabled(false)
part:setCapInsets(cc.rect(0,0,85,85))
part:setTouchEnabled(false)
part:setLayoutComponentEnabled(true)
part:setName("part")
part:setLocalZOrder(0)
part:setTag(12)
part:setCascadeColorEnabled(true)
part:setCascadeOpacityEnabled(true)
part:setVisible(true)
part:setAnchorPoint(0.5, 0.5)
part:setPosition(56.5, 56.5)
part:setScaleX(1)
part:setScaleY(1)
part:setRotation(0)
part:setRotationSkewX(0)
part:setRotationSkewY(0)
part:setOpacity(255)
part:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(part)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.7522)
layout:setPercentHeight(0.7522)

layout:setSize(cc.size(85, 85))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(14)
layout:setRightMargin(14)
layout:setTopMargin(14)
layout:setBottomMargin(14)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
partbg:addChild(part)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

