--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create name_txt
local name_txt = ccui.Text:create()
name_txt:ignoreContentAdaptWithSize(true)
name_txt:setTextAreaSize(cc.size(0, 0))
name_txt:setFontName("Resources/font/ttf/black_body.TTF")
name_txt:setFontSize(22)
name_txt:setString([[玩家名字七个字]])
name_txt:setTextHorizontalAlignment(0)
name_txt:setTextVerticalAlignment(0)
name_txt:setTouchScaleChangeEnabled(false)
name_txt:setFlippedX(false)
name_txt:setFlippedY(false)
name_txt:enableOutline(cc.c4b(0, 0, 0, 255), 1)
name_txt:setTouchEnabled(false)
name_txt:setLayoutComponentEnabled(true)
name_txt:setName("name_txt")
name_txt:setLocalZOrder(0)
name_txt:setTag(108)
name_txt:setCascadeColorEnabled(true)
name_txt:setCascadeOpacityEnabled(true)
name_txt:setVisible(true)
name_txt:setAnchorPoint(0.5, 0.5)
name_txt:setPosition(178.6026, 19)
name_txt:setScaleX(1)
name_txt:setScaleY(1)
name_txt:setRotation(0)
name_txt:setRotationSkewX(0)
name_txt:setRotationSkewY(0)
name_txt:setOpacity(255)
name_txt:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(name_txt)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(154, 27))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(94.6026)
layout:setRightMargin(-262.6026)
layout:setTopMargin(-32.5)
layout:setBottomMargin(5.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(name_txt)

--Create p_count
local p_count = ccui.Text:create()
p_count:ignoreContentAdaptWithSize(true)
p_count:setTextAreaSize(cc.size(0, 0))
p_count:setFontName("Resources/font/ttf/black_body.TTF")
p_count:setFontSize(22)
p_count:setString([[244]])
p_count:setTextHorizontalAlignment(0)
p_count:setTextVerticalAlignment(0)
p_count:setTouchScaleChangeEnabled(false)
p_count:setFlippedX(false)
p_count:setFlippedY(false)
p_count:enableOutline(cc.c4b(0, 0, 0, 255), 1)
p_count:setTouchEnabled(false)
p_count:setLayoutComponentEnabled(true)
p_count:setName("p_count")
p_count:setLocalZOrder(0)
p_count:setTag(109)
p_count:setCascadeColorEnabled(true)
p_count:setCascadeOpacityEnabled(true)
p_count:setVisible(true)
p_count:setAnchorPoint(0.5, 0.5)
p_count:setPosition(342.5001, 19)
p_count:setScaleX(1)
p_count:setScaleY(1)
p_count:setRotation(0)
p_count:setRotationSkewX(0)
p_count:setRotationSkewY(0)
p_count:setOpacity(255)
p_count:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(p_count)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(45, 27))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(318.5001)
layout:setRightMargin(-366.5001)
layout:setTopMargin(-32.5)
layout:setBottomMargin(5.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(p_count)

--Create reward_txt
local reward_txt = ccui.Text:create()
reward_txt:ignoreContentAdaptWithSize(true)
reward_txt:setTextAreaSize(cc.size(0, 0))
reward_txt:setFontName("Resources/font/ttf/black_body.TTF")
reward_txt:setFontSize(22)
reward_txt:setString([[244]])
reward_txt:setTextHorizontalAlignment(0)
reward_txt:setTextVerticalAlignment(0)
reward_txt:setTouchScaleChangeEnabled(false)
reward_txt:setFlippedX(false)
reward_txt:setFlippedY(false)
reward_txt:enableOutline(cc.c4b(0, 0, 0, 255), 1)
reward_txt:setTouchEnabled(false)
reward_txt:setLayoutComponentEnabled(true)
reward_txt:setName("reward_txt")
reward_txt:setLocalZOrder(0)
reward_txt:setTag(110)
reward_txt:setCascadeColorEnabled(true)
reward_txt:setCascadeOpacityEnabled(true)
reward_txt:setVisible(true)
reward_txt:setAnchorPoint(1, 0.5)
reward_txt:setPosition(496.8267, 19)
reward_txt:setScaleX(1)
reward_txt:setScaleY(1)
reward_txt:setRotation(0)
reward_txt:setRotationSkewX(0)
reward_txt:setRotationSkewY(0)
reward_txt:setOpacity(255)
reward_txt:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(reward_txt)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(45, 27))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(448.8267)
layout:setRightMargin(-496.8267)
layout:setTopMargin(-32.5)
layout:setBottomMargin(5.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(reward_txt)

--Create Sprite_10
local Sprite_10 = cc.Sprite:create("Resources/common/icon/coin/1a.png")
Sprite_10:setName("Sprite_10")
Sprite_10:setLocalZOrder(0)
Sprite_10:setTag(111)
Sprite_10:setCascadeColorEnabled(true)
Sprite_10:setCascadeOpacityEnabled(true)
Sprite_10:setVisible(true)
Sprite_10:setAnchorPoint(0.5, 0.5)
Sprite_10:setPosition(516.3844, 18.7143)
Sprite_10:setScaleX(1)
Sprite_10:setScaleY(1)
Sprite_10:setRotation(0)
Sprite_10:setRotationSkewX(0)
Sprite_10:setRotationSkewY(0)
Sprite_10:setOpacity(255)
Sprite_10:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_10)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(32, 26))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(500.3844)
layout:setRightMargin(-532.3844)
layout:setTopMargin(-31.7143)
layout:setBottomMargin(5.7143)
Sprite_10:setFlippedX(false)
Sprite_10:setFlippedY(false)
Node:addChild(Sprite_10)

--Create rank_txt
local rank_txt = ccui.Text:create()
rank_txt:ignoreContentAdaptWithSize(true)
rank_txt:setTextAreaSize(cc.size(0, 0))
rank_txt:setFontName("Resources/font/ttf/black_body.TTF")
rank_txt:setFontSize(22)
rank_txt:setString([[1]])
rank_txt:setTextHorizontalAlignment(0)
rank_txt:setTextVerticalAlignment(0)
rank_txt:setTouchScaleChangeEnabled(false)
rank_txt:setFlippedX(false)
rank_txt:setFlippedY(false)
rank_txt:enableOutline(cc.c4b(0, 0, 0, 255), 1)
rank_txt:setTouchEnabled(false)
rank_txt:setLayoutComponentEnabled(true)
rank_txt:setName("rank_txt")
rank_txt:setLocalZOrder(0)
rank_txt:setTag(112)
rank_txt:setCascadeColorEnabled(true)
rank_txt:setCascadeOpacityEnabled(true)
rank_txt:setVisible(true)
rank_txt:setAnchorPoint(0, 0.5)
rank_txt:setPosition(28.5, 19)
rank_txt:setScaleX(1)
rank_txt:setScaleY(1)
rank_txt:setRotation(0)
rank_txt:setRotationSkewX(0)
rank_txt:setRotationSkewY(0)
rank_txt:setOpacity(255)
rank_txt:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(rank_txt)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(13, 27))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(28.5)
layout:setRightMargin(-41.5)
layout:setTopMargin(-31.5)
layout:setBottomMargin(6.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(rank_txt)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

