--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create bg
cc.SpriteFrameCache:getInstance():addSpriteFrames("legion/res/club/legion_club.plist")
local bg = cc.Sprite:createWithSpriteFrameName("legion/res/club/farm_pic.png")
bg:setName("bg")
bg:setLocalZOrder(0)
bg:setTag(64)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setVisible(true)
bg:setAnchorPoint(0.5, 0.5)
bg:setPosition(424, 81)
bg:setScaleX(1)
bg:setScaleY(1)
bg:setRotation(0)
bg:setRotationSkewX(0)
bg:setRotationSkewY(0)
bg:setOpacity(255)
bg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(834, 149))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(7)
layout:setRightMargin(-841)
layout:setTopMargin(-155.5)
layout:setBottomMargin(6.5)
bg:setFlippedX(false)
bg:setFlippedY(false)
Node:addChild(bg)

--Create lock_status
cc.SpriteFrameCache:getInstance():addSpriteFrames("legion/res/club/legion_club.plist")
local lock_status = cc.Sprite:createWithSpriteFrameName("legion/res/club/unlock_pic.png")
lock_status:setName("lock_status")
lock_status:setLocalZOrder(0)
lock_status:setTag(66)
lock_status:setCascadeColorEnabled(true)
lock_status:setCascadeOpacityEnabled(true)
lock_status:setVisible(true)
lock_status:setAnchorPoint(0.5, 0.5)
lock_status:setPosition(760.5, 73)
lock_status:setScaleX(1)
lock_status:setScaleY(1)
lock_status:setRotation(0)
lock_status:setRotationSkewX(0)
lock_status:setRotationSkewY(0)
lock_status:setOpacity(255)
lock_status:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(lock_status)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.9119)
layout:setPositionPercentY(0.4899)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(78, 78))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(721.5)
layout:setRightMargin(34.5)
layout:setTopMargin(37)
layout:setBottomMargin(34)
lock_status:setFlippedX(false)
lock_status:setFlippedY(false)
bg:addChild(lock_status)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

