--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
Layer:setLocalZOrder(0)

--Create BG
local BG = ccui.ImageView:create()
BG:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/img/common_img.plist")
BG:loadTexture("Resources/common/img/Base_0006.png",1)

BG:setFlippedX(false)
BG:setFlippedY(false)

BG:setScale9Enabled(true)
BG:setCapInsets(cc.rect(32,32,34,34))
BG:setTouchEnabled(false)
BG:setLayoutComponentEnabled(true)
BG:setName("BG")
BG:setLocalZOrder(0)
BG:setTag(77)
BG:setCascadeColorEnabled(true)
BG:setCascadeOpacityEnabled(true)
BG:setVisible(true)
BG:setAnchorPoint(0.5, 0.5)
BG:setPosition(540, 360)
BG:setScaleX(1)
BG:setScaleY(1)
BG:setRotation(0)
BG:setRotationSkewX(0)
BG:setRotationSkewY(0)
BG:setOpacity(255)
BG:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(BG)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.6398)
layout:setPercentHeight(0.5722)

layout:setSize(cc.size(691, 412))

layout:setHorizontalEdge(3)
layout:setVerticalEdge(0)
layout:setLeftMargin(194.5)
layout:setRightMargin(194.5)
layout:setTopMargin(154)
layout:setBottomMargin(154)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Layer:addChild(BG)

--Create Times
local Times = ccui.Text:create()
Times:ignoreContentAdaptWithSize(true)
Times:setTextAreaSize(cc.size(0, 0))
Times:setFontName("Resources/font/ttf/black_body_2.TTF")
Times:setFontSize(22)
Times:setString([[您的排名：]])
Times:setTextHorizontalAlignment(0)
Times:setTextVerticalAlignment(0)
Times:setTouchScaleChangeEnabled(false)
Times:setFlippedX(false)
Times:setFlippedY(false)
Times:enableOutline(cc.c4b(0, 0, 0, 255), 1)
Times:setTouchEnabled(false)
Times:setLayoutComponentEnabled(true)
Times:setName("Times")
Times:setLocalZOrder(0)
Times:setTag(78)
Times:setCascadeColorEnabled(true)
Times:setCascadeOpacityEnabled(true)
Times:setVisible(true)
Times:setAnchorPoint(0.5, 0.5)
Times:setPosition(130, -27.9503)
Times:setScaleX(1)
Times:setScaleY(1)
Times:setRotation(0)
Times:setRotationSkewX(0)
Times:setRotationSkewY(0)
Times:setOpacity(255)
Times:setColor(cc.c3b(255, 255, 208))
layout = ccui.LayoutComponent:bindLayoutComponent(Times)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.1881)
layout:setPositionPercentY(-0.0678)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(110, 27))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(75)
layout:setRightMargin(506)
layout:setTopMargin(426.4503)
layout:setBottomMargin(-41.4503)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
BG:addChild(Times)

--Create Rank
local Rank = ccui.Text:create()
Rank:ignoreContentAdaptWithSize(true)
Rank:setTextAreaSize(cc.size(0, 0))
Rank:setFontName("Resources/font/ttf/black_body_2.TTF")
Rank:setFontSize(22)
Rank:setString([[7000]])
Rank:setTextHorizontalAlignment(0)
Rank:setTextVerticalAlignment(0)
Rank:setTouchScaleChangeEnabled(false)
Rank:setFlippedX(false)
Rank:setFlippedY(false)
Rank:enableOutline(cc.c4b(0, 0, 0, 255), 1)
Rank:setTouchEnabled(false)
Rank:setLayoutComponentEnabled(true)
Rank:setName("Rank")
Rank:setLocalZOrder(0)
Rank:setTag(79)
Rank:setCascadeColorEnabled(true)
Rank:setCascadeOpacityEnabled(true)
Rank:setVisible(true)
Rank:setAnchorPoint(0, 0.5)
Rank:setPosition(181, -27.9503)
Rank:setScaleX(1)
Rank:setScaleY(1)
Rank:setRotation(0)
Rank:setRotationSkewX(0)
Rank:setRotationSkewY(0)
Rank:setOpacity(255)
Rank:setColor(cc.c3b(44, 255, 72))
layout = ccui.LayoutComponent:bindLayoutComponent(Rank)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.2619)
layout:setPositionPercentY(-0.0678)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(53, 27))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(181)
layout:setRightMargin(457)
layout:setTopMargin(426.4503)
layout:setBottomMargin(-41.4503)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
BG:addChild(Rank)

--Create Times_0
local Times_0 = ccui.Text:create()
Times_0:ignoreContentAdaptWithSize(true)
Times_0:setTextAreaSize(cc.size(0, 0))
Times_0:setFontName("Resources/font/ttf/black_body_2.TTF")
Times_0:setFontSize(22)
Times_0:setString([[02:00:00]])
Times_0:setTextHorizontalAlignment(0)
Times_0:setTextVerticalAlignment(0)
Times_0:setTouchScaleChangeEnabled(false)
Times_0:setFlippedX(false)
Times_0:setFlippedY(false)
Times_0:enableOutline(cc.c4b(0, 0, 0, 255), 1)
Times_0:setTouchEnabled(false)
Times_0:setLayoutComponentEnabled(true)
Times_0:setName("Times_0")
Times_0:setLocalZOrder(0)
Times_0:setTag(80)
Times_0:setCascadeColorEnabled(true)
Times_0:setCascadeOpacityEnabled(true)
Times_0:setVisible(false)
Times_0:setAnchorPoint(0.5, 0.5)
Times_0:setPosition(531, -27.9503)
Times_0:setScaleX(1)
Times_0:setScaleY(1)
Times_0:setRotation(0)
Times_0:setRotationSkewX(0)
Times_0:setRotationSkewY(0)
Times_0:setOpacity(255)
Times_0:setColor(cc.c3b(255, 255, 208))
layout = ccui.LayoutComponent:bindLayoutComponent(Times_0)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.7685)
layout:setPositionPercentY(-0.0678)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(93, 27))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(484.5)
layout:setRightMargin(113.5)
layout:setTopMargin(426.4503)
layout:setBottomMargin(-41.4503)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
BG:addChild(Times_0)

--Create Sprite_11
cc.SpriteFrameCache:getInstance():addSpriteFrames("earth_soul/res/res.plist")
local Sprite_11 = cc.Sprite:createWithSpriteFrameName("earth_soul/res/10.png")
Sprite_11:setName("Sprite_11")
Sprite_11:setLocalZOrder(0)
Sprite_11:setTag(82)
Sprite_11:setCascadeColorEnabled(true)
Sprite_11:setCascadeOpacityEnabled(true)
Sprite_11:setVisible(true)
Sprite_11:setAnchorPoint(0.5, 0.5)
Sprite_11:setPosition(345.5, 387)
Sprite_11:setScaleX(1)
Sprite_11:setScaleY(1)
Sprite_11:setRotation(0)
Sprite_11:setRotationSkewX(0)
Sprite_11:setRotationSkewY(0)
Sprite_11:setOpacity(255)
Sprite_11:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_11)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.9393)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(680, 43))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(5.5)
layout:setRightMargin(5.5)
layout:setTopMargin(3.5)
layout:setBottomMargin(365.5)
Sprite_11:setFlippedX(false)
Sprite_11:setFlippedY(false)
BG:addChild(Sprite_11)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

