--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
Layer:setLocalZOrder(0)

--Create Node_3
local Node_3=cc.Node:create()
Node_3:setName("Node_3")
Node_3:setLocalZOrder(0)
Node_3:setTag(306)
Node_3:setCascadeColorEnabled(true)
Node_3:setCascadeOpacityEnabled(true)
Node_3:setVisible(true)
Node_3:setAnchorPoint(0, 0)
Node_3:setPosition(220, 100)
Node_3:setScaleX(1)
Node_3:setScaleY(1)
Node_3:setRotation(0)
Node_3:setRotationSkewX(0)
Node_3:setRotationSkewY(0)
Node_3:setOpacity(255)
Node_3:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Node_3)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(220)
layout:setPositionPercentY(100)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(220)
layout:setRightMargin(-219)
layout:setTopMargin(-99)
layout:setBottomMargin(100)
Layer:addChild(Node_3)

--Create titleBg
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/img/common_img.plist")
local titleBg = cc.Sprite:createWithSpriteFrameName("Resources/common/img/biaotidi.png")
titleBg:setName("titleBg")
titleBg:setLocalZOrder(0)
titleBg:setTag(122)
titleBg:setCascadeColorEnabled(true)
titleBg:setCascadeOpacityEnabled(true)
titleBg:setVisible(true)
titleBg:setAnchorPoint(0.5, 0.5)
titleBg:setPosition(20.5, 25)
titleBg:setScaleX(1)
titleBg:setScaleY(1)
titleBg:setRotation(0)
titleBg:setRotationSkewX(0)
titleBg:setRotationSkewY(0)
titleBg:setOpacity(255)
titleBg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(titleBg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(354, 37))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-156.5)
layout:setRightMargin(-197.5)
layout:setTopMargin(-43.5)
layout:setBottomMargin(6.5)
titleBg:setFlippedX(false)
titleBg:setFlippedY(false)
Node_3:addChild(titleBg)

--Create titleTxt
local titleTxt = ccui.Text:create()
titleTxt:ignoreContentAdaptWithSize(true)
titleTxt:setTextAreaSize(cc.size(0, 0))
titleTxt:setFontName("Resources/font/ttf/black_body_2.TTF")
titleTxt:setFontSize(20)
titleTxt:setString([[第1轮扫荡]])
titleTxt:setTextHorizontalAlignment(1)
titleTxt:setTextVerticalAlignment(1)
titleTxt:setTouchScaleChangeEnabled(false)
titleTxt:setFlippedX(false)
titleTxt:setFlippedY(false)
titleTxt:enableOutline(cc.c4b(0, 0, 0, 255), 1)
titleTxt:setTouchEnabled(false)
titleTxt:setLayoutComponentEnabled(true)
titleTxt:setName("titleTxt")
titleTxt:setLocalZOrder(0)
titleTxt:setTag(142)
titleTxt:setCascadeColorEnabled(true)
titleTxt:setCascadeOpacityEnabled(true)
titleTxt:setVisible(true)
titleTxt:setAnchorPoint(0.5, 0.5)
titleTxt:setPosition(24.6605, 24.5009)
titleTxt:setScaleX(1)
titleTxt:setScaleY(1)
titleTxt:setRotation(0)
titleTxt:setRotationSkewX(0)
titleTxt:setRotationSkewY(0)
titleTxt:setOpacity(255)
titleTxt:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(titleTxt)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(94, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-22.3395)
layout:setRightMargin(-71.6605)
layout:setTopMargin(-37.0009)
layout:setBottomMargin(12.0009)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node_3:addChild(titleTxt)

--Create item2
local item2=cc.Node:create()
item2:setName("item2")
item2:setLocalZOrder(0)
item2:setTag(167)
item2:setCascadeColorEnabled(true)
item2:setCascadeOpacityEnabled(true)
item2:setVisible(true)
item2:setAnchorPoint(0, 0)
item2:setPosition(-5, -41)
item2:setScaleX(1)
item2:setScaleY(1)
item2:setRotation(0)
item2:setRotationSkewX(0)
item2:setRotationSkewY(0)
item2:setOpacity(255)
item2:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(item2)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-5)
layout:setRightMargin(5)
layout:setTopMargin(41)
layout:setBottomMargin(-41)
Node_3:addChild(item2)

--Create item1
local item1=cc.Node:create()
item1:setName("item1")
item1:setLocalZOrder(0)
item1:setTag(166)
item1:setCascadeColorEnabled(true)
item1:setCascadeOpacityEnabled(true)
item1:setVisible(true)
item1:setAnchorPoint(0, 0)
item1:setPosition(-108, -41)
item1:setScaleX(1)
item1:setScaleY(1)
item1:setRotation(0)
item1:setRotationSkewX(0)
item1:setRotationSkewY(0)
item1:setOpacity(255)
item1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(item1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-108)
layout:setRightMargin(108)
layout:setTopMargin(41)
layout:setBottomMargin(-41)
Node_3:addChild(item1)

--Create item3
local item3=cc.Node:create()
item3:setName("item3")
item3:setLocalZOrder(0)
item3:setTag(171)
item3:setCascadeColorEnabled(true)
item3:setCascadeOpacityEnabled(true)
item3:setVisible(true)
item3:setAnchorPoint(0, 0)
item3:setPosition(100, -41)
item3:setScaleX(1)
item3:setScaleY(1)
item3:setRotation(0)
item3:setRotationSkewX(0)
item3:setRotationSkewY(0)
item3:setOpacity(255)
item3:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(item3)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(100)
layout:setRightMargin(-100)
layout:setTopMargin(41)
layout:setBottomMargin(-41)
Node_3:addChild(item3)

--Create item4
local item4=cc.Node:create()
item4:setName("item4")
item4:setLocalZOrder(0)
item4:setTag(170)
item4:setCascadeColorEnabled(true)
item4:setCascadeOpacityEnabled(true)
item4:setVisible(true)
item4:setAnchorPoint(0, 0)
item4:setPosition(203, -41)
item4:setScaleX(1)
item4:setScaleY(1)
item4:setRotation(0)
item4:setRotationSkewX(0)
item4:setRotationSkewY(0)
item4:setOpacity(255)
item4:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(item4)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(203)
layout:setRightMargin(-203)
layout:setTopMargin(41)
layout:setBottomMargin(-41)
Node_3:addChild(item4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

