--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
Layer:setLocalZOrder(0)

--Create Node_1
local Node_1=cc.Node:create()
Node_1:setName("Node_1")
Node_1:setLocalZOrder(0)
Node_1:setTag(162)
Node_1:setCascadeColorEnabled(true)
Node_1:setCascadeOpacityEnabled(true)
Node_1:setVisible(true)
Node_1:setAnchorPoint(0, 0)
Node_1:setPosition(485, 281.5)
Node_1:setScaleX(1)
Node_1:setScaleY(1)
Node_1:setRotation(0)
Node_1:setRotationSkewX(0)
Node_1:setRotationSkewY(0)
Node_1:setOpacity(255)
Node_1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Node_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(0, 0))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(485)
layout:setRightMargin(485)
layout:setTopMargin(281.5)
layout:setBottomMargin(281.5)
Layer:addChild(Node_1)

--Create BG
local BG = ccui.ImageView:create()
BG:ignoreContentAdaptWithSize(false)
BG:loadTexture("legion_generaltion/res/ZhengZhanKuangQu.jpg",0)

BG:setFlippedX(false)
BG:setFlippedY(false)

BG:setScale9Enabled(false)
BG:setCapInsets(cc.rect(0,0,1280,720))
BG:setTouchEnabled(false)
BG:setLayoutComponentEnabled(true)
BG:setName("BG")
BG:setLocalZOrder(0)
BG:setTag(2)
BG:setCascadeColorEnabled(true)
BG:setCascadeOpacityEnabled(true)
BG:setVisible(true)
BG:setAnchorPoint(0.5, 0.5)
BG:setPosition(0, 0)
BG:setScaleX(1)
BG:setScaleY(1)
BG:setRotation(0)
BG:setRotationSkewX(0)
BG:setRotationSkewY(0)
BG:setOpacity(255)
BG:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(BG)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(1280, 720))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-640)
layout:setRightMargin(-640)
layout:setTopMargin(-360)
layout:setBottomMargin(-360)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node_1:addChild(BG)

--Create Tips1
local Tips1 = ccui.Text:create()
Tips1:ignoreContentAdaptWithSize(true)
Tips1:setTextAreaSize(cc.size(0, 0))
Tips1:setFontName("Resources/font/ttf/black_body_2.TTF")
Tips1:setFontSize(24)
Tips1:setString([[1.活动期间内收获或抢夺稀有矿区时，
 触发特殊事件会额外获得购物卡和积分。
2.抢夺成功后，获得的购物卡和积分通过
邮件发放
3.不同的特殊事件获得的购物卡和积分数量
不同.
4.抢夺非满矿是不会获得购物卡和积分的
哦.]])
Tips1:setTextHorizontalAlignment(0)
Tips1:setTextVerticalAlignment(0)
Tips1:setTouchScaleChangeEnabled(false)
Tips1:setFlippedX(false)
Tips1:setFlippedY(false)
Tips1:setTouchEnabled(false)
Tips1:setLayoutComponentEnabled(true)
Tips1:setName("Tips1")
Tips1:setLocalZOrder(0)
Tips1:setTag(23)
Tips1:setCascadeColorEnabled(true)
Tips1:setCascadeOpacityEnabled(true)
Tips1:setVisible(true)
Tips1:setAnchorPoint(0, 0.5)
Tips1:setPosition(-213.9274, 41.9459)
Tips1:setScaleX(1)
Tips1:setScaleY(1)
Tips1:setRotation(0)
Tips1:setRotationSkewX(0)
Tips1:setRotationSkewY(0)
Tips1:setOpacity(255)
Tips1:setColor(cc.c3b(255, 165, 0))
layout = ccui.LayoutComponent:bindLayoutComponent(Tips1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(454, 216))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-213.9274)
layout:setRightMargin(-264.0726)
layout:setTopMargin(-149.9459)
layout:setBottomMargin(-66.0541)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node_1:addChild(Tips1)

--Create Tips2
local Tips2 = ccui.Text:create()
Tips2:ignoreContentAdaptWithSize(true)
Tips2:setTextAreaSize(cc.size(0, 0))
Tips2:setFontName("Resources/font/ttf/black_body_2.TTF")
Tips2:setFontSize(24)
Tips2:setString([[1. 军团押运物资品质越高，获得积分和
购物卡收益越大。
2. 押运被抢劫后，购物卡、积分收益
减半。
3. 成功抢劫押运后，抢劫者会获得押
运的一半购物卡和积分。
4. 押运获得的购物卡会通过邮件发放，
积分会直接记在活动中。]])
Tips2:setTextHorizontalAlignment(0)
Tips2:setTextVerticalAlignment(0)
Tips2:setTouchScaleChangeEnabled(false)
Tips2:setFlippedX(false)
Tips2:setFlippedY(false)
Tips2:setTouchEnabled(false)
Tips2:setLayoutComponentEnabled(true)
Tips2:setName("Tips2")
Tips2:setLocalZOrder(0)
Tips2:setTag(175)
Tips2:setCascadeColorEnabled(true)
Tips2:setCascadeOpacityEnabled(true)
Tips2:setVisible(false)
Tips2:setAnchorPoint(0, 0.5)
Tips2:setPosition(-208.6768, 40.1784)
Tips2:setScaleX(1)
Tips2:setScaleY(1)
Tips2:setRotation(0)
Tips2:setRotationSkewX(0)
Tips2:setRotationSkewY(0)
Tips2:setOpacity(255)
Tips2:setColor(cc.c3b(255, 165, 0))
layout = ccui.LayoutComponent:bindLayoutComponent(Tips2)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(414, 216))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-208.6768)
layout:setRightMargin(-205.3232)
layout:setTopMargin(-148.1784)
layout:setBottomMargin(-67.8216)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node_1:addChild(Tips2)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("legion_generaltion/res/meinv.png",0)

Image_1:setFlippedX(false)
Image_1:setFlippedY(false)

Image_1:setScale9Enabled(false)
Image_1:setCapInsets(cc.rect(0,0,411,474))
Image_1:setTouchEnabled(false)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setLocalZOrder(0)
Image_1:setTag(51)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setVisible(true)
Image_1:setAnchorPoint(0.5, 0.5)
Image_1:setPosition(269.9222, -17.3656)
Image_1:setScaleX(1)
Image_1:setScaleY(1)
Image_1:setRotation(0)
Image_1:setRotationSkewX(0)
Image_1:setRotationSkewY(0)
Image_1:setOpacity(255)
Image_1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(2.7039)
layout:setPercentHeight(7.1818)

layout:setSize(cc.size(411, 474))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(64.4222)
layout:setRightMargin(-475.4222)
layout:setTopMargin(-219.6344)
layout:setBottomMargin(-254.3656)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node_1:addChild(Image_1)

--Create jinrubtn
local jinrubtn = ccui.Button:create()
jinrubtn:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
jinrubtn:loadTextureNormal("Resources/common/button/btn_3.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
jinrubtn:loadTexturePressed("Resources/common/button/qq2.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
jinrubtn:loadTextureDisabled("Resources/common/button/anniuhui.png",1)
jinrubtn:setTitleFontSize(14)
jinrubtn:setTitleText("")
jinrubtn:setTitleColor(cc.c3b(65, 65, 70))
jinrubtn:setFlippedX(false)
jinrubtn:setFlippedY(false)
jinrubtn:setScale9Enabled(true)
jinrubtn:setCapInsets(cc.rect(15,11,122,44))
jinrubtn:setBright(true)
jinrubtn:setTouchEnabled(true)
jinrubtn:setLayoutComponentEnabled(true)
jinrubtn:setName("jinrubtn")
jinrubtn:setLocalZOrder(0)
jinrubtn:setTag(50)
jinrubtn:setCascadeColorEnabled(true)
jinrubtn:setCascadeOpacityEnabled(true)
jinrubtn:setVisible(true)
jinrubtn:setAnchorPoint(0.5, 0.5)
jinrubtn:setPosition(-2.2995, -172.4298)
jinrubtn:setScaleX(1)
jinrubtn:setScaleY(1)
jinrubtn:setRotation(0)
jinrubtn:setRotationSkewX(0)
jinrubtn:setRotationSkewY(0)
jinrubtn:setOpacity(255)
jinrubtn:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(jinrubtn)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(152, 66))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-78.2995)
layout:setRightMargin(-73.7005)
layout:setTopMargin(139.4298)
layout:setBottomMargin(-205.4298)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node_1:addChild(jinrubtn)

--Create qiandao_1
local qiandao_1 = cc.Sprite:create("legion_generaltion/res/jinru.png")
qiandao_1:setName("qiandao_1")
qiandao_1:setLocalZOrder(0)
qiandao_1:setTag(100)
qiandao_1:setCascadeColorEnabled(true)
qiandao_1:setCascadeOpacityEnabled(true)
qiandao_1:setVisible(true)
qiandao_1:setAnchorPoint(0.5, 0.5)
qiandao_1:setPosition(76, 33)
qiandao_1:setScaleX(1)
qiandao_1:setScaleY(1)
qiandao_1:setRotation(0)
qiandao_1:setRotationSkewX(0)
qiandao_1:setRotationSkewY(0)
qiandao_1:setOpacity(255)
qiandao_1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(qiandao_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.3553)
layout:setPercentHeight(0.3333)

layout:setSize(cc.size(62, 22))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(45)
layout:setRightMargin(45)
layout:setTopMargin(22)
layout:setBottomMargin(22)
qiandao_1:setFlippedX(false)
qiandao_1:setFlippedY(false)
jinrubtn:addChild(qiandao_1)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize(cc.size(0, 0))
Text_1:setFontSize(20)
Text_1:setString([[活动结束后购物卡将全部清空]])
Text_1:setTextHorizontalAlignment(0)
Text_1:setTextVerticalAlignment(0)
Text_1:setTouchScaleChangeEnabled(false)
Text_1:setFlippedX(false)
Text_1:setFlippedY(false)
Text_1:setTouchEnabled(false)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setLocalZOrder(0)
Text_1:setTag(85)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setVisible(true)
Text_1:setAnchorPoint(0.5, 0.5)
Text_1:setPosition(5.0226, -238.1763)
Text_1:setScaleX(1)
Text_1:setScaleY(1)
Text_1:setRotation(0)
Text_1:setRotationSkewX(0)
Text_1:setRotationSkewY(0)
Text_1:setOpacity(255)
Text_1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(260, 23))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(-124.9774)
layout:setRightMargin(-135.0226)
layout:setTopMargin(226.6763)
layout:setBottomMargin(-249.6763)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node_1:addChild(Text_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

