--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
Layer:setLocalZOrder(0)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("discount_sale/res/1.jpg",0)

bg:setFlippedX(false)
bg:setFlippedY(false)

bg:setScale9Enabled(false)
bg:setCapInsets(cc.rect(0,0,757,635))
bg:setTouchEnabled(false)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setLocalZOrder(0)
bg:setTag(17)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setVisible(true)
bg:setAnchorPoint(0.5, 0.5)
bg:setPosition(540, 360)
bg:setScaleX(1)
bg:setScaleY(1)
bg:setRotation(0)
bg:setRotationSkewX(0)
bg:setRotationSkewY(0)
bg:setOpacity(255)
bg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5)
layout:setPositionPercentY(0.5)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.7009)
layout:setPercentHeight(0.8819)

layout:setSize(cc.size(757, 635))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(161.5)
layout:setRightMargin(161.5)
layout:setTopMargin(42.5)
layout:setBottomMargin(42.5)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Layer:addChild(bg)

--Create bg_close
local bg_close = ccui.ImageView:create()
bg_close:ignoreContentAdaptWithSize(false)
bg_close:loadTexture("Resources/common/bg/c_12.png",0)

bg_close:setFlippedX(false)
bg_close:setFlippedY(false)

bg_close:setScale9Enabled(false)
bg_close:setCapInsets(cc.rect(0,0,2,2))
bg_close:setTouchEnabled(false)
bg_close:setLayoutComponentEnabled(true)
bg_close:setName("bg_close")
bg_close:setLocalZOrder(0)
bg_close:setTag(18)
bg_close:setCascadeColorEnabled(true)
bg_close:setCascadeOpacityEnabled(true)
bg_close:setVisible(true)
bg_close:setAnchorPoint(0.4502, 0.5)
bg_close:setPosition(706.4507, 605.6803)
bg_close:setScaleX(1.3669)
bg_close:setScaleY(1.0995)
bg_close:setRotation(0)
bg_close:setRotationSkewX(0)
bg_close:setRotationSkewY(0)
bg_close:setOpacity(255)
bg_close:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bg_close)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.9332)
layout:setPositionPercentY(0.9538)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.0625)
layout:setPercentHeight(0.0781)

layout:setSize(cc.size(60, 50))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(679.4387)
layout:setRightMargin(17.5613)
layout:setTopMargin(4.3197)
layout:setBottomMargin(580.6803)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(bg_close)

--Create time
local time = ccui.Text:create()
time:ignoreContentAdaptWithSize(true)
time:setTextAreaSize(cc.size(0, 0))
time:setFontName("Resources/black_body.TTF")
time:setFontSize(22)
time:setString([[10天18:06:51]])
time:setTextHorizontalAlignment(0)
time:setTextVerticalAlignment(0)
time:setTouchScaleChangeEnabled(false)
time:setFlippedX(false)
time:setFlippedY(false)
time:setTouchEnabled(false)
time:setLayoutComponentEnabled(true)
time:setName("time")
time:setLocalZOrder(0)
time:setTag(19)
time:setCascadeColorEnabled(true)
time:setCascadeOpacityEnabled(true)
time:setVisible(true)
time:setAnchorPoint(0.5, 0.5)
time:setPosition(454.906, 536.2696)
time:setScaleX(1)
time:setScaleY(1)
time:setRotation(0)
time:setRotationSkewX(0)
time:setRotationSkewY(0)
time:setOpacity(255)
time:setColor(cc.c3b(25, 234, 29))
layout = ccui.LayoutComponent:bindLayoutComponent(time)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.6009)
layout:setPositionPercentY(0.8445)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(152, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(378.906)
layout:setRightMargin(226.094)
layout:setTopMargin(86.2304)
layout:setBottomMargin(523.7696)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(time)

--Create title
local title = ccui.Text:create()
title:ignoreContentAdaptWithSize(true)
title:setTextAreaSize(cc.size(0, 0))
title:setFontName("Resources/font/ttf/black_body_2.TTF")
title:setFontSize(22)
title:setString([[各类物资道具折扣出售，总有让您满意的一款！不要错过机会哦！]])
title:setTextHorizontalAlignment(0)
title:setTextVerticalAlignment(0)
title:setTouchScaleChangeEnabled(false)
title:setFlippedX(false)
title:setFlippedY(false)
title:enableOutline(cc.c4b(0, 0, 0, 255), 1)
title:setTouchEnabled(false)
title:setLayoutComponentEnabled(true)
title:setName("title")
title:setLocalZOrder(0)
title:setTag(20)
title:setCascadeColorEnabled(true)
title:setCascadeOpacityEnabled(true)
title:setVisible(true)
title:setAnchorPoint(0.5, 0.5)
title:setPosition(392.1761, 502.0714)
title:setScaleX(1)
title:setScaleY(1)
title:setRotation(0)
title:setRotationSkewX(0)
title:setRotationSkewY(0)
title:setOpacity(255)
title:setColor(cc.c3b(241, 227, 183))
layout = ccui.LayoutComponent:bindLayoutComponent(title)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5181)
layout:setPositionPercentY(0.7907)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(638, 27))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(73.1761)
layout:setRightMargin(45.8239)
layout:setTopMargin(119.4286)
layout:setBottomMargin(488.5714)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(title)

--Create Panel
local Panel = ccui.Layout:create()
Panel:ignoreContentAdaptWithSize(false)

Panel:setClippingEnabled(false)
Panel:setBackGroundImageCapInsets(cc.rect(0,0,1,1))
Panel:setBackGroundColor(cc.c3b(150, 200, 255))
Panel:setBackGroundColor(cc.c3b(150, 200, 255),cc.c3b(255, 255, 255))
Panel:setBackGroundColorVector(cc.p(0,1))
Panel:setBackGroundColorType(0)
Panel:setBackGroundColorOpacity(102)
Panel:setBackGroundImageScale9Enabled(false)

Panel:setTouchEnabled(true)
Panel:setLayoutComponentEnabled(true)
Panel:setName("Panel")
Panel:setLocalZOrder(0)
Panel:setTag(21)
Panel:setCascadeColorEnabled(true)
Panel:setCascadeOpacityEnabled(true)
Panel:setVisible(true)
Panel:setAnchorPoint(0, 0)
Panel:setPosition(31.5858, 31.7381)
Panel:setScaleX(1)
Panel:setScaleY(1)
Panel:setRotation(0)
Panel:setRotationSkewX(0)
Panel:setRotationSkewY(0)
Panel:setOpacity(255)
Panel:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Panel)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.0417)
layout:setPositionPercentY(0.05)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0.7292)
layout:setPercentHeight(0.6953)

layout:setSize(cc.size(700, 445))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(31.5858)
layout:setRightMargin(25.4142)
layout:setTopMargin(158.2619)
layout:setBottomMargin(31.7381)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(Panel)

--Create Text_1
local Text_1 = ccui.Text:create()
Text_1:ignoreContentAdaptWithSize(true)
Text_1:setTextAreaSize(cc.size(0, 0))
Text_1:setFontName("Resources/black_body.TTF")
Text_1:setFontSize(22)
Text_1:setString([[活动倒计时:]])
Text_1:setTextHorizontalAlignment(0)
Text_1:setTextVerticalAlignment(0)
Text_1:setTouchScaleChangeEnabled(false)
Text_1:setFlippedX(false)
Text_1:setFlippedY(false)
Text_1:setTouchEnabled(false)
Text_1:setLayoutComponentEnabled(true)
Text_1:setName("Text_1")
Text_1:setLocalZOrder(0)
Text_1:setTag(22)
Text_1:setCascadeColorEnabled(true)
Text_1:setCascadeOpacityEnabled(true)
Text_1:setVisible(true)
Text_1:setAnchorPoint(0.5, 0.5)
Text_1:setPosition(318.2207, 536.688)
Text_1:setScaleX(1)
Text_1:setScaleY(1)
Text_1:setRotation(0)
Text_1:setRotationSkewX(0)
Text_1:setRotationSkewY(0)
Text_1:setOpacity(255)
Text_1:setColor(cc.c3b(23, 238, 38))
layout = ccui.LayoutComponent:bindLayoutComponent(Text_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.4204)
layout:setPositionPercentY(0.8452)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(118, 25))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(259.2207)
layout:setRightMargin(379.7793)
layout:setTopMargin(85.812)
layout:setBottomMargin(524.188)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
bg:addChild(Text_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

