--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
Node:setLocalZOrder(0)

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("discount_sale/res/ui.plist")
bg:loadTexture("discount_sale/res/12.png",1)

bg:setFlippedX(false)
bg:setFlippedY(false)

bg:setScale9Enabled(false)
bg:setCapInsets(cc.rect(0,0,707,165))
bg:setTouchEnabled(false)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setLocalZOrder(0)
bg:setTag(8)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setVisible(true)
bg:setAnchorPoint(0.5, 0.5)
bg:setPosition(354, 81.5)
bg:setScaleX(1)
bg:setScaleY(1)
bg:setRotation(0)
bg:setRotationSkewX(0)
bg:setRotationSkewY(0)
bg:setOpacity(255)
bg:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(707, 165))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(0.5)
layout:setRightMargin(-707.5)
layout:setTopMargin(-164)
layout:setBottomMargin(-1)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(bg)

--Create Sprite_1
cc.SpriteFrameCache:getInstance():addSpriteFrames("discount_sale/res/ui.plist")
local Sprite_1 = cc.Sprite:createWithSpriteFrameName("discount_sale/res/2.png")
Sprite_1:setName("Sprite_1")
Sprite_1:setLocalZOrder(0)
Sprite_1:setTag(9)
Sprite_1:setCascadeColorEnabled(true)
Sprite_1:setCascadeOpacityEnabled(true)
Sprite_1:setVisible(true)
Sprite_1:setAnchorPoint(0.5, 0.5)
Sprite_1:setPosition(464.0605, 89.3856)
Sprite_1:setScaleX(1)
Sprite_1:setScaleY(1)
Sprite_1:setRotation(0)
Sprite_1:setRotationSkewX(0)
Sprite_1:setRotationSkewY(0)
Sprite_1:setOpacity(255)
Sprite_1:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_1)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(84, 85))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(422.0605)
layout:setRightMargin(-506.0605)
layout:setTopMargin(-131.8856)
layout:setBottomMargin(46.8856)
Sprite_1:setFlippedX(false)
Sprite_1:setFlippedY(false)
Node:addChild(Sprite_1)

--Create countNum
cc.SpriteFrameCache:getInstance():addSpriteFrames("discount_sale/res/ui.plist")
local countNum = cc.Sprite:createWithSpriteFrameName("discount_sale/res/zhekou4.png")
countNum:setName("countNum")
countNum:setLocalZOrder(0)
countNum:setTag(10)
countNum:setCascadeColorEnabled(true)
countNum:setCascadeOpacityEnabled(true)
countNum:setVisible(true)
countNum:setAnchorPoint(0.5, 0.5)
countNum:setPosition(443.7465, 83.0373)
countNum:setScaleX(1)
countNum:setScaleY(1)
countNum:setRotation(0)
countNum:setRotationSkewX(0)
countNum:setRotationSkewY(0)
countNum:setOpacity(255)
countNum:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(countNum)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(39, 38))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(424.2465)
layout:setRightMargin(-463.2465)
layout:setTopMargin(-102.0373)
layout:setBottomMargin(64.0373)
countNum:setFlippedX(false)
countNum:setFlippedY(false)
Node:addChild(countNum)

--Create Sprite_3
cc.SpriteFrameCache:getInstance():addSpriteFrames("discount_sale/res/ui.plist")
local Sprite_3 = cc.Sprite:createWithSpriteFrameName("discount_sale/res/9.png")
Sprite_3:setName("Sprite_3")
Sprite_3:setLocalZOrder(0)
Sprite_3:setTag(11)
Sprite_3:setCascadeColorEnabled(true)
Sprite_3:setCascadeOpacityEnabled(true)
Sprite_3:setVisible(true)
Sprite_3:setAnchorPoint(0.5, 0.5)
Sprite_3:setPosition(488.1832, 93.1945)
Sprite_3:setScaleX(1)
Sprite_3:setScaleY(1)
Sprite_3:setRotation(0)
Sprite_3:setRotationSkewX(0)
Sprite_3:setRotationSkewY(0)
Sprite_3:setOpacity(255)
Sprite_3:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_3)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(54, 40))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(461.1832)
layout:setRightMargin(-515.1832)
layout:setTopMargin(-113.1945)
layout:setBottomMargin(73.1945)
Sprite_3:setFlippedX(false)
Sprite_3:setFlippedY(false)
Node:addChild(Sprite_3)

--Create SunNum
local SunNum = ccui.Text:create()
SunNum:ignoreContentAdaptWithSize(true)
SunNum:setTextAreaSize(cc.size(0, 0))
SunNum:setFontName("Resources/font/ttf/black_body.TTF")
SunNum:setFontSize(28)
SunNum:setString([[10/10]])
SunNum:setTextHorizontalAlignment(0)
SunNum:setTextVerticalAlignment(0)
SunNum:setTouchScaleChangeEnabled(false)
SunNum:setFlippedX(false)
SunNum:setFlippedY(false)
SunNum:enableOutline(cc.c4b(0, 0, 0, 255), 1)
SunNum:setTouchEnabled(false)
SunNum:setLayoutComponentEnabled(true)
SunNum:setName("SunNum")
SunNum:setLocalZOrder(0)
SunNum:setTag(12)
SunNum:setCascadeColorEnabled(true)
SunNum:setCascadeOpacityEnabled(true)
SunNum:setVisible(true)
SunNum:setAnchorPoint(0.5, 0.5)
SunNum:setPosition(601.4514, 118.6213)
SunNum:setScaleX(1)
SunNum:setScaleY(1)
SunNum:setRotation(0)
SunNum:setRotationSkewX(0)
SunNum:setRotationSkewY(0)
SunNum:setOpacity(255)
SunNum:setColor(cc.c3b(10, 235, 18))
layout = ccui.LayoutComponent:bindLayoutComponent(SunNum)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(80, 34))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(561.4514)
layout:setRightMargin(-641.4514)
layout:setTopMargin(-135.6213)
layout:setBottomMargin(101.6213)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(SunNum)

--Create Buy_bt
local Buy_bt = ccui.Button:create()
Buy_bt:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
Buy_bt:loadTextureNormal("Resources/common/button/btn_3.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
Buy_bt:loadTexturePressed("Resources/common/button/anniuhong02.png",1)
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/button/common_button.plist")
Buy_bt:loadTextureDisabled("Resources/common/button/anniuhui.png",1)
Buy_bt:setTitleFontSize(14)
Buy_bt:setTitleText("")
Buy_bt:setTitleColor(cc.c3b(65, 65, 70))
Buy_bt:setFlippedX(false)
Buy_bt:setFlippedY(false)
Buy_bt:setScale9Enabled(true)
Buy_bt:setCapInsets(cc.rect(15,11,122,44))
Buy_bt:setBright(true)
Buy_bt:setTouchEnabled(true)
Buy_bt:setLayoutComponentEnabled(true)
Buy_bt:setName("Buy_bt")
Buy_bt:setLocalZOrder(0)
Buy_bt:setTag(13)
Buy_bt:setCascadeColorEnabled(true)
Buy_bt:setCascadeOpacityEnabled(true)
Buy_bt:setVisible(true)
Buy_bt:setAnchorPoint(0.5, 0.5)
Buy_bt:setPosition(603.7209, 64.9328)
Buy_bt:setScaleX(0.9332)
Buy_bt:setScaleY(1)
Buy_bt:setRotation(0)
Buy_bt:setRotationSkewX(0)
Buy_bt:setRotationSkewY(0)
Buy_bt:setOpacity(255)
Buy_bt:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Buy_bt)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0)
layout:setPositionPercentY(0)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(152, 66))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(527.7209)
layout:setRightMargin(-679.7209)
layout:setTopMargin(-97.9328)
layout:setBottomMargin(31.9328)
layout:setStretchWidthEnabled(false)
layout:setStretchHeightEnabled(false)
Node:addChild(Buy_bt)

--Create Sprite_4
cc.SpriteFrameCache:getInstance():addSpriteFrames("Resources/common/txt/common_txt.plist")
local Sprite_4 = cc.Sprite:createWithSpriteFrameName("Resources/common/txt/goumai2.png")
Sprite_4:setName("Sprite_4")
Sprite_4:setLocalZOrder(0)
Sprite_4:setTag(14)
Sprite_4:setCascadeColorEnabled(true)
Sprite_4:setCascadeOpacityEnabled(true)
Sprite_4:setVisible(true)
Sprite_4:setAnchorPoint(0.5, 0.5)
Sprite_4:setPosition(78.4683, 33.7423)
Sprite_4:setScaleX(1)
Sprite_4:setScaleY(1)
Sprite_4:setRotation(0)
Sprite_4:setRotationSkewX(0)
Sprite_4:setRotationSkewY(0)
Sprite_4:setOpacity(255)
Sprite_4:setColor(cc.c3b(255, 255, 255))
layout = ccui.LayoutComponent:bindLayoutComponent(Sprite_4)
layout:setPositionPercentXEnabled(false)
layout:setPositionPercentYEnabled(false)
layout:setPositionPercentX(0.5162)
layout:setPositionPercentY(0.5112)
layout:setPercentWidthEnabled(false)
layout:setPercentHeightEnabled(false)
layout:setPercentWidth(0)
layout:setPercentHeight(0)

layout:setSize(cc.size(75, 29))

layout:setHorizontalEdge(0)
layout:setVerticalEdge(0)
layout:setLeftMargin(40.9683)
layout:setRightMargin(36.0317)
layout:setTopMargin(17.7577)
layout:setBottomMargin(19.2423)
Sprite_4:setFlippedX(false)
Sprite_4:setFlippedY(false)
Buy_bt:addChild(Sprite_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1)
--Create Animation List

result['root'] = Node
return result;
end

return Result

